OpenZWave/open-zwave

cpp/hidapi/libusb/hid.c
Fix issue #462 
The patch attached to the ticket alters the checked version. For valid versions, see: https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/versions.html
=> Fix for issue 462

ChangeLog, cpp/src/platform/unix/LogImpl.cpp
Otherwise we use an uninited pFile in Write, potentially causing crash
=> unix LogImpl: ensure pFile is NULL if no filename was given

config/dragontech/wd-100.xml, config/manufacturer_specific.xml
This addresses the issues of the manufacturer not in the correct spot as well as defines the one association group that the switch supports.  This goes with issues #502
=> Add support for the Dragon Tech In wall dimmer to the open zwave database v3

config/manufacturer_specific.xml, config/vision/zd2102.xml
Right now the vision zd2102 gen5 is working good with Issue-352-Security branch.
Attached the config file pull.
The old zd2102 and the new gen5 zd2102-5 devices share the same product id.
Moreover the manual (http://www.lorenzhd.com/thesmartesthouse/downloads/zd-2102-eu-5-door-window-sensor.pdf) and the pepper1 database (http://www.pepper1.net/zwavedb/device/547) are discordant.
The official zd2102 manual reports only one configuration parameter, instead pepper1 reports 2 config parameters (without descriptions).
Anyway I used the manual as official documentation source.
Try the patch and let me know.
King regards
=> Patch vision security zd2102 gen5

dotnet/examples/OZWForm/src/ControllerCommandDlg.cs, dotnet/examples/OZWForm/src/MainForm.Designer.cs, dotnet/examples/OZWForm/src/MainForm.cs, dotnet/src/ZWManager.cpp, dotnet/src/ZWManager.h, dotnet/src/ZWNotification.h
Update:
Had to revert to a new branch and re-add all my changed files, because my working branch of my fork got completely messed up. This new branch should now only contain the necessary files and updates.
Old updates: 
(from new to old)
*Updated OZWForm with a new menu item to add secure devices
*Edited .Net wrapper and OZWForm to use the new methods:
Edited the .Net wrapper and OZWForm to work with the new methods. For
now I have used only one way of adding nodes, which always uses the
security enabled way. I have no other devices, so can't test if this is
right or not. Furthermore, I split the implementation and definition of
the methods between the ZWManager.cpp and ZWManager.h. But the methods
are just one line calls to the manager, and as some other methods like
that in ZWManager …
=> Reverted and readded changed files

config/cooper/RF9505-T.xml, config/cooper/RF9540-N.xml, config/manufacturer_specific.xml
This relates to issues #563.  It adds database support for the Cooper Aspire RF 9540 all load dimmer as well as add configuration support for the Cooper Aspire RF 9505 split duplex outlet
=> add database support for the Cooper all load dimmer and configuration for Cooper outlet

cpp/build/windows/vs2010/OpenZWave.vcxproj
The MinOZW solution incorporates the OpenZWave project and its build is broken due to the SolutionDir macro.
Changed $(SolutionDir) to $(ProjectDir) to fix
=> Fixed windows build event (winversion.cpp generation)

cpp/src/command_classes/CommandClasses.cpp, cpp/src/command_classes/DeviceResetLocally.cpp, cpp/src/command_classes/DeviceResetLocally.h
Initial version for the DeviceResetLocally CommandClass.
When a node is reset is will send out a DeviceResetLocally message telling the controller the node has been reset and left the network.
Upon receiving this goodbye message we will try to send a NoOp message so the controller knows the node has gone. Next we ask the controller to remove the failed node. 
When the node answers the NoOp the removal will fail.
=> DeviceResetLocally Command Class

config/manufacturer_specific.xml, config/zwave.me/ZME_06433.xml
* Add 05433 part number to description (I'm not sure of the history of the 06433 part, seems to only exist in old references but I didn't remove it).
* Correct a few options with incorrect values.
* Add new options that only exist with the latest firmware v1.8 (scene control, min/max brightness etc)
=> Update ZME_06433 with bugfixes and new options

config/qubino/ZMNHBA2.xml
without the mapping the device reports tree in stead of two switches due to a incorrect endpoint mapping.
=> config ZMNHBA2: correct instance/endpoint mapping

config/manufacturer_specific.xml
It's just a new specification for the popular Fibaro FGR221 using firmware 109.
=> config for Fibaro FGR221 (firmware 109)

ChangeLog, config/manufacturer_specific.xml, config/merten/50x5xx.xml
There was no configuration file for Merten 50x5xx roller shutter
modules. Added those as proposed here:
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
=> Added configuration for Merten 50x5xx Roller Shutter Module

ChangeLog, dotnet/src/ZWManager.cpp, dotnet/src/ZWManager.h
Make sure we use a fully qualified namespace for arrays, so VS2015 doesn't get confused.
=> Issue #446 - Visual Studio 2015 Breakage

cpp/build/Makefile, cpp/build/libopenzwave.pc.in
Precise git version is needed to be able to scan and enable the new security API in openzwave-shared. I've also added the shared conf dir (PREFIX/etc/openzwave) and documentation (PREFIX/share/doc/openzwave-<version>)
=> PR: add some useful variables in pkg-config

config/linear/PD300Z-2.xml, config/linear/WD500Z-1.xml, config/manufacturer_specific.xml
Two configuration parameters, and an override for the Level's max value. Both the module and the in-wall switch work the same.
=> Added configuration files for Linear dimmers

cpp/src/Notification.cpp, cpp/src/Notification.h
`const` needs to be added to the function signature (it returns a one-use message string anyway: no mutations whatsoever), otherwise I cannot call it from the callback handler, as I'm getting a [passing const discards qualifiers](http://stackoverflow.com/questions/5973427/error-passing-xxx-as-this-argument-of-xxx-discards-qualifiers?rq=1)
this is because the callback handler signature defines `_pNotification` as `const`
```
typedef void(* 	pfnOnNotification_t) (Notification const *_pNotification, void *_context)
```
=> constify Notification::GetAsString() 

cpp/build/Makefile, cpp/build/support.mk, cpp/examples/MinOZW/Makefile, cpp/hidapi/libusb/hid.c
Some minor fixes to make build work on FreeBSD again.
Not sure on backwards compatibility on the iconv thing, but other FreeBSD ports seems to have been fully changed (i.e no conditionals): https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=199099, so I'd say openzwave should do the same?
=> FreeBSD fixes

cpp/src/Manager.cpp, cpp/src/Manager.h, cpp/src/value_classes/ValueList.cpp, cpp/src/value_classes/ValueList.h
This may be useful to upper SW stack or bindings to retrieve the list of integer values from list type values. This could make it more convenient for subsequent ozw.setValue() call, instead of getting string labels of the value list.
=> add manager interface and value list method to retrieve list of integer values from value list

ChangeLog, config/manufacturer_specific.xml, config/merten/507801.xml, distfiles.mk
I have added support for the Plug-in Roller Shutter Module (507801) from Merten. 
Some documentation of this module can be found at http://www.merten.com/uploads/tx_seqdownload/V5078_581_00_web_01.pdf
The functionality is similar to the Merten 50x5xx, which is already supported.
=> Added support for Merten Plug-in Roller Shutter Module.

cpp/src/Manager.cpp, dotnet/src/ZWManager.cpp, dotnet/src/ZWManager.h
Hi Justin, 
can you accept this patch. It keeps the dotnet wrapper sync with the c++ codebase.
I've added the Manager::GetValueListValues() function introduced by the commit 8cc839a8a08acf7d723241f779d8a72c221382f7.
Thanks.
=> update dotnet wrapper

cpp/hidapi/libusb/hid.c
Without this fix, I get:
openzwave/cpp/hidapi/libusb/hid.c:372:18: error: passing
'char **' to parameter of type 'const char **' discards qualifiers in nested
pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
res = iconv(ic, &inptr, &inbytes, &outptr, &outbytes);
^~~~~~
/usr/include/iconv.h:56:47: note: passing argument to parameter here
size_t  iconv(iconv_t, const char ** __restrict,
from FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
=> hid.c: make inptr in get_usb_string const

cpp/build/Makefile, cpp/examples/MinOZW/Makefile, cpp/hidapi/libusb/hid.c
Revert hid.c change in d78c7d0, and enforce older FreeBSD versions to
use libiconv from ports instead of old non-posix from base.
Fixes #748, tested on both 10.1 and 10.2. Should work on 9.3 too.
=> Multi-platform compatible FreeBSD build fix for iconv

config/manufacturer_specific.xml
Add type/id for Australian FGD212 dimmer.
=> Add support for Fibaru FGD212 AH (Australian version).

config/manufacturer_specific.xml
The Devolo Home Control Radiator Thermostat is identical to the Danfoss Z Thermostat. There are some firmware differences, but it is functionally 100% identical to the Danfoss model, works fine with the danfoss/z.xml and has even the Danfoss manufacturer ID.
So it would be nice to add the configuration to the config file, it's just the one line with the different product id.
=> Add Devolo Home Control Radiator Thermostat

config/aeotec/minimote.xml
the default is group mode, but the xml config is inverted and the default is scene mode.. that is incorrect.
with index=250 value=1 it was impossible to update this parameter, see this thread and the posts leading up to it: https://www.domoticz.com/forum/viewtopic.php?f=6&t=2283&start=40#p71143
this very small change has proven to work for numerous people, the previous value gives nothing but headaches.
You can see the default was inverted with this commit, appears to be an accident: https://github.com/nayrnet/open-zwave/commit/a47eda41790c488f60f92e203c8e784f88629652
=> fixed minimote default value

cpp/src/Driver.cpp
I detected a device that from times to times send a UPDATE_STATE_NEW_ID_ASSIGNED when it didn't happen, This device sends a request where the old id is equal to the current id so, IMHO there is no need to add and remove the device with initnode since it may generate a lot of remove and add events on a consumer application.
This situation may happen in order to a faulty device firmware, but since it comes from a commercial product that any other person has bought I guess that this small fix wont hurt no one
=> drive.cpp UPDATE_STATE_NEW_ID_ASSIGNED fix

config/everspring/an181.xml, config/manufacturer_specific.xml, distfiles.mk
Tested with latest snapshot of Domoticz and works reasonable OK. 
All control seems to work ok, but the meter support does not work for kWh or power factor.
Not sure if the Notification reports (device powered on, or overload situation) works.
If communication is temporarily lost, or device experience power failure: then Domoticz reports the switch as ON when communication is restored even though it may be in OFF position... -> Is the Notification Report (device powered on) misinterpreted as the switch is in ON position?
=> New device: Everspring AN181 Miniplug with meter function

config/manufacturer_specific.xml
Attach the right name and config to the version of the VRMX1-1LZ that I got (newer rev maybe? Ordered at http://smile.amazon.com/Leviton-VRMX1-1LZ-Universal-Magnetic-Voltage/dp/B005Y8JC6Q).
=> Device Support: Leviton VRMX1-1LZ - additional hardware id

config/manufacturer_specific.xml
New RaZBerry board has an updated ID. No differences known between this one and the older ID=0001, but I've added 2016 into the name to differentiate.
=> Add RaZBerry Pi board ID=0002 (Same as ID=0001)

cpp/src/command_classes/UserCode.cpp
Signed-off-by: Bin Li <bin.li@windriver.com>
This patch fixes the issue 847 "segment fault when getting zero size user code packet".
https://github.com/OpenZWave/open-zwave/issues/847
=> fix for issue 847

cpp/hidapi/hidapi/hidapi.h, cpp/src/platform/windows/TimeStampImpl.cpp
Also fixed the hidapi dll export, causing the final windows application to contain hid exports.
This was already merged some time ago, but somehow reverted back ?
=> Fixed crash on Windows systems. Timestamp (m_stamp)not parsed as pointer (Used in the Control Panel)

config/manufacturer_specific.xml, config/nexia/db100z.xml, distfiles.mk
Add configuration support for the Nexia DB100Z Z-Wave Doorbell Sensor.
It's only got one config param according to http://products.z-wavealliance.org/products/1349/configs, pretty simple/boring. Device works well otherwise - alarm class notifications (class 113, index 11, value of 0/1) for the doorbell state, and battery class for the battery reports, works great after discovery.
=> Device Support: Nexia DB100Z Z-Wave Doorbell Sensor configuration params

cpp/hidapi/linux/hid.c
Define __GNU_SOURCE in cpp/hidapi/linux/hid.c (like already done in
cpp/hidapi/libusb/hid.c) to fix implicit declaration of wcsdup function
=> Fix warning on wcsdup implicit declaration

cpp/build/Makefile
sysconfdir and includedir can be overriden by the build system however those values weren't used when building libopenzwave.pc
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
=> Fix libopenzwave.pc when using custom values

cpp/build/support.mk
Add "--git-dir ./.git" to ensure the correct git repository path is used (this
fix a bug when trying to add openzwave to buildroot build system)
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
=> Ensure correct git repository path

Makefile
Fix "cpp/src/vers.cpp" target in main Makefile
Now it is possible to generate vers.cpp without building whole project by executing "make cpp/src/vers.cpp"
Fixes #881
=> Fix vers.cpp target

config/manufacturer_specific.xml
I noticed that Ecolink Motion Sensor (https://www.amazon.com/Ecolink-Z-Wave-Motion-Detector-PIRZWAVE2-ECO/dp/B00FB1TBKS) was appearing with the wrong name. It was appearing as "Door/Window Sensor". I happen to also have several Ecolink Door/Window Sensors (https://www.amazon.com/Ecolink-Z-Wave-Window-Sensor-DWZWAVE2-ECO/dp/B00HPIYJWU) and they were not being recognized.
This PR fixes both problems. The PIR Motion Sensor now appears with proper name and Door/Sensor were added to the database.
=> Added Ecolink door/window sensor and fixed Ecolink PIR Motion sensor

config/manufacturer_specific.xml
Adds support for the AU/NZ frequency of the Fibaro Door and Window
Sensor, FGK101.
=> Add support for AU/NZ Frequency Fibaro DW Sensor

cpp/src/Node.cpp, cpp/src/command_classes/WakeUp.cpp, cpp/src/command_classes/WakeUp.h
This fixes some devices that don't automatically goto sleep after the inclusion process has completed and our QueryStages is complete.
=> Ensure we send a WakeUpNoMoreInfo at end of QueryStages

dotnet/src/ZWManager.h
Added new methods in the dotnet adapter : IsNodeZWavePlus, GetNodeDeviceType, GetNodeDeviceTypeString, GetNodeRole, GetNodeRoleString, GetNodePlusType, GetNodePlusTypeString, GetValueMin, GetValueMax, IsValueWriteOnly, GetChangeVerified, GetGroupLabel. Some comments fix also and const params added.
Fixed also some comments and unifiying some space between ) and {
=> Sync dot net zw manager bundle

dotnet/src/ZWManager.h
Added Invalid value in the ZWLogLevel Enum in DotNet to keep Enum in sync with the CPP enum
=> Sync DotNet ZWLogLevel Enum with the CPP enum

config/manufacturer_specific.xml
Adds support to OpenZave to recognise the Australian/New Zealand version
of the Remotec ZXT-120 A?C IR Controller.
=> Add support for AU/NZ Frequency Remotec ZXT120 IR Controller

config/manufacturer_specific.xml
I purchased a new FortrezZ MIMOlite and noticed that it appears as product type 0453 and ID 0111 instead of ID 0110.
=> Update manufacturer_specific.xml to add another FortrezZ MIMOlite ID

cpp/examples/MinOZW/Makefile
LIBDIR was used in cpp/examples/MinOZW/Makefile to add dynamic
libraries. However, as it was unset by default, the cross-compilation
could fail if the host had a library such as libnss3.so in /.
To fix this issue, this patch sets LIBDIR to top_buildir if it is unset
Fixes:
http://autobuild.buildroot.net/results/68719fdf1320a69310bada6d3c47654dacdb5898
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
=> Fix compilation of MinOZW

cpp/build/Makefile
Hi,
a previous FreeBSD related change lost the -soname linker flag. This patch re-introduces it.
An unrelated question: What is the current version number / release plan?
The changelog has a V1.5 title which seems to get continually updated. But there is a V1.5 git tag pointing to 2 commits after V1.4 (a lot of commits ago).
I'm working on the FreeBSD package, it would be good to know what's to expect :)
Thanks!
=> Fix FreeBSD soname

config/manufacturer_specific.xml
Added support for the GE 12730 Fan Control switch, which mirrors the GE 12724 Dimmer switch in functionality.
=> Add GE 12730 Fan Control

cpp/src/value_classes/ValueList.cpp
When setting a configuration parameter List with a value not starting at 0 i got an "invalid Index" error (or something like that).
This was because the `ValueList::SetByValue()` got (in my case) the value 2 and used that as index, which did not exist.
By using `GetItemIdxByValue()` this was fixed.
```				
<Value type="list" genre="config" instance="1" index="5" label="Command Options" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="1" max="2" vindex="0" size="1">
<Help>Which commands to send when PIR motion sensor triggered</Help>
<Item label="Basic Set (default)" value="1" />
<Item label="Binary Sensor Report" value="2" />
</Value>
```
=> Fix ValueList::SetByValue for values not starting at 0

cpp/src/Driver.cpp
It was possible for `m_currentControllerCommand` to be NULL, thus accessing it causes a segmentation fault. Moving the log output inside the if where this is checked.
=> Fix null pointer

cpp/src/Node.cpp
Nonce handling has a bug.  If one is generated with the same first byte as an earlier in the cache (ie. m_nonces[i][0] == m_nonces[j][0] where i<j) and is used to encrypt a packet, then GetNonceKey() will pick the first (i) for decryption.  This causes the decryption to generate garbage, the MAC comparison to fail, and the packet to be dropped.
The fix is to require the first byte of each nonce be unique during generation.  This is actually required by the security protocol.
There are two other tweaks in this patch.  First, it also requires the first byte be non-zero.  This requirement is coming from a long-time ZWave developer; I haven't been able to find it documented anywhere.  (To not require this use the equation for the other bytes for the first, ie. 256*rand()/(RAND_MAX+1.0).) …
=> fix to Nonce generation

cpp/src/ZWSecurity.cpp
Code filled the sender portion of the intialization vector with 0xaa (with a random seed commented out).  It needs to be random bytes.  Because the IV is used twice and overwritten in-between by the aes_mode_reset() call, we need to create a copy for generating the MAC.
There's also a spelling typo in an unrelated comment that got fixed.
=> replace fixed value initialization vector (for encryption key) 

config/fibaro/fgs213.xml, config/fibaro/fgs223.xml
As the title says, this fixes typo's and faulty search/replaces in the FGS-213 and FGS-223 config files.
=> Fix typo's in Fibaro FGS-213 & FGS-223 config files

config/fibaro/fgwpfzw5.xml, config/manufacturer_specific.xml
Added the file provided in the google discussion: https://groups.google.com/forum/#!topic/openzwave/4FmIYvXS9dY
Fixed some typos and performed a pretty print.
The previous file for the fibaro wall plug was not working correctly. (Power metering not reporting, incorrect parameters, ...)
=> Added support for Fibaro Wall plug Gen5 (FGWPF-102)

config/manufacturer_specific.xml
Thanks Vincent Ou (Remotec) for providing the list of
product types and confirming that there are no differences
in firmware.
Probably need to change config to work around issue #1063,
but that does not appear to be region-specific.
=> Add ZXT-120 product types for other regions

config/manufacturer_specific.xml, config/schlage/BE468CAM619.xml
This adds information about the Schlage BE468 lock. It is nearly identical to the BE469, but it is missing a few of the features.
=> Add Schlage BE468 lock

config/manufacturer_specific.xml
When a zwave controller is acting as a secondary device on a network controlled by the Samsung SmartThings hub, their main controller shows as unknown. This addition resolves that.
=> Added Samsung Smarthings Hub

config/manufacturer_specific.xml
GE 12729 is the switch-style equivalent to the GE 12724 paddle-style dimmer switch
=> Add GE 12729 Dimmer Switch

config/manufacturer_specific.xml
Maps the Device ID for the AU/NZ Frequenxy version of the NEOCam Flood
Sensor to the appropriate configuration file.
=> Add support for AU/NZ Frequency NEOCam Flood Sensor

config/manufacturer_specific.xml
Ecolink TILTZWAVE2.5-ECO[1] is the z-wave plus update to the TILTZWAVE2-ECO sensor.
[1] - http://products.z-wavealliance.org/products/1501
=> Add Ecolink TILTZWAVE2.5-ECO Garage Door Sensor

config/manufacturer_specific.xml, config/popp/009402.xml
Support for Popp: 10 Year Smoke Detector and Siren
Requires PCB 1.5 and firmware 1.14 (or higher)
=> Added support for POPP 009402

cpp/src/Driver.cpp, cpp/src/platform/unix/MutexImpl.cpp
My OpenZwave stopped responding multiple times a day. And after a certain time i was seeing alot of `2016-12-21 06:21:20.520 Error, ERROR: Not enough space in stream buffer`.  
Looking into this I found out that the driverThread was hanging while trying to get a lock for m_nodeMutex.
```
2017-01-20 10:54:57.871 Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=1
2017-01-20 10:54:57.874 Always,       Locking 827319692 from void OpenZWave::Driver::CheckCompletedNodeQueries()
2017-01-20 10:54:57.876 Always,       Locking 818914372 from bool OpenZWave::Manager::IsNodeFailed(uint32, uint8)
2017-01-20 10:54:57.878 Always,       Locking 827319692 from void OpenZWave::Driver::CheckCompletedNodeQueries() ... done with ret: true
2017-01-20 10:54:57.882 Always, …
```
=> possible fix (or workaround) for a deadlock

cpp/src/platform/unix/SerialControllerImpl.cpp
POSIX.1-2001 requires sys/select.h for select() and friends.
Compile-tested on glibc and musl, runtime tested on musl.
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>
=> unix: fix compilation against musl libc

cpp/build/Makefile
When not on Darwin, SHARED_LIB_NAME is libopenzwave.so.$(VERSION). Use
this variable in LDFLAGS on FreeBSD and Linux, instead of duplicating
its value.
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>
=> Makefile: use SHARED_LIB_NAME variable in LDFLAGS

debian/libopenzwave1.3-dev.install, debian/rules
Without this, `dpkg-buildpackage` fails with the following:
```
make[1]: Entering directory '/home/ubuntu/open-zwave'
CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 VERSION_MAJ=1 VERSION_MIN=4 VERSION_REV=79 PREFIX=/usr SYSCONFDIR=/etc/openzwave instlibdir=/usr/lib/x86_64-linux-gnu/ make
/bin/sh: 1: -D_FORTIFY_SOURCE=2: not found
debian/rules:27: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 127
make[1]: Leaving directory '/home/ubuntu/open-zwave'
debian/rules:24: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```
and then fails with this:
```
dh_install: libopenzwave1.3-dev missing files: usr/lib*/pkgconfig/libopenzwave.pc
dh_install: missing files, aborting …
```
=> Fix Debian package build

cpp/src/Driver.cpp
Fixed parsing of poll_interval_between in Driver::ReadConfig().
=> Fixed poll_interval_between parsing in Driver::ReadConfig

config/manufacturer_specific.xml
http://products.z-wavealliance.org/products/1702
Product Type ID: 0x2002
Product ID: 0x0205 
Brand Name: Vision
Product Identifier: ZP3102US-5 
http://products.z-wavealliance.org/products/703
Product Type ID: 0x2002
Product ID: 0x0202 
Brand Name: Vision
Product Identifier: ZP3102EU 
after further inspection, looks like some of these devices share the same device id and types, although clearly a different description. Perhaps solution is to just remove the country indicator all together? i'll leave that decision up to the person approving this merge
http://products.z-wavealliance.org/products/1070
=> zp3102us device incorrectly labelled EU

ChangeLog, config/manufacturer_specific.xml
The values for the CT30 thermostat that I have were not present in the manufacturer specific list, so I added them in.  Let me know if anything is missing.
=> Added additional config entry for 2GIG CT-30 Radio Thermostat

config/manufacturer_specific.xml
Enerwave ZWN-RSM1 PLUS—Smart Single Relay Switch Module 
http://enerwaveautomation.com/products/zwnrsm1s/ 
http://enerwaveautomation.com/wp-content/uploads/products/zwnrsm1s/ZWN-RSM1-Plus-0208160043-02.pdf
=> add ZWN-RSM1 plus

config/manufacturer_specific.xml
I have device TKBHOME TZ69F and it is the same like device described in file: wenzhou/tz69.xml,
but other type and id. 
I have duplicated TZ69 entry with type and id my device is reporting and now it is working for me (tested in my application).
=> Added TKBHOME TZ69F alias

config/homeseer/hs-wd100plus.xml
The HS-WD100+ dimmer supports setting the ramp rate separately for local (at switch) control and remote commands.
=> Adds remote ramp configuration for wd100+

config/manufacturer_specific.xml
Add additional identifier for the Fibaro FGMS001-ZW5 Sensor.
=> Add additional identifier for the Fibaro FGMS001-ZW5 Sensor.

config/manufacturer_specific.xml
Made a mistake in #1189 and found it only after submitting that. Now it's fixed and even double checked with the actual device.
=> fixed two typos in hkzw-SO05

cpp/build/winRT/vs2015/OpenZWave.vcxproj
Visual Studio doesn't install v10240 SDK by default any longer, so most people will experience problems with opening this project. 
The MinVersion is still 10240 and is still supported to run on, so there's no breaking changes from this.
The only difference is you will now have to have the 14393 SDK installed on your PC, instead of 10240 (which has now been standard for VS for a long time)
=> Updated UWP SDK target version to be compiled against 14393 instead of 10240

cpp/build/winRT/vs2015/OpenZWave.vcxproj
Builds on top of #1198.
Use the default platform toolset instead of a hardcoded value, which allows compiling will multiple different versions of Visual Studio (VS2017 and futures etc)
=> Vs2017 support

.gitignore, cpp/build/windows/mingw32/Makefile, cpp/src/platform/windows/EventImpl.h, cpp/src/platform/windows/LogImpl.cpp, cpp/src/platform/windows/LogImpl.h, cpp/src/platform/windows/SerialControllerImpl.h, cpp/src/platform/windows/TimeStampImpl.cpp
Several fixes for the MinGW Makefile and some source files to make the project build cleanly (again?) with MinGW, including cross builds from Linux and FreeBSD.
See the commit titles and descriptions for details.
=> Fixes for MinGW

BSDmakefile
The default BSD make (at least on FreeBSD) is not GNU make, nor is it compatible with it. This new BSDmakefile will case BSD make to invoke GNU make.
=> Add BSDmakefile

.gitignore, config/fibaro/fgrm222.xml, cpp/src/Msg.cpp, cpp/src/Msg.h, cpp/src/command_classes/CommandClasses.cpp, cpp/src/command_classes/ManufacturerProprietary.cpp, cpp/src/command_classes/ManufacturerProprietary.h
As discussed some time ago in the forum: The Fibaro FGRM-222 Roller Shutter 2 is using the COMMAND_CLASS_MANUFACTURER_PROPRIETARY to indicate the tilt angle of the slats. This is only transmitted when activating the venetian blind mode and setting the report type to "Fibaro Command class".
@Fishwaldo 
As I messed up my branch completely, it was easier to create a new, clean one. So this is the continuation of pull request https://github.com/OpenZWave/open-zwave/pull/1203
=> added new command class ManufacturerProprietary for Fibaro FGRM-222 (part 2)

config/danfoss/rsroom.xml
Added decimal value descriptors for command class thermostat setpoint. This makes it possible to set the setpoint with decimal values and not only integers.
=> Update rsroom.xml to support decimal values

cpp/build/windows/mingw32/Makefile, cpp/src/platform/windows/EventImpl.h, cpp/src/platform/windows/LogImpl.h, cpp/src/platform/windows/SerialControllerImpl.h, cpp/src/platform/windows/TimeStampImpl.cpp
Updated MinGW Makefile - added AES files to compilation.
Fixed inclusion on windows header file to lower case to be able to compile this under Linux (cross compilation).
=> Updated MinGW compilation

cpp/src/value_classes/ValueByte.cpp
Writing a byte to the string stream ends up converting it as a character. It's cast to an integer here since it's the numeric value we want to see.
Fixes #466
=> Fix logging for byte values

cpp/build/winRT/vs2015/OpenZWave.vcxproj, cpp/build/winRT/vs2015/OpenZWave.vcxproj.filters, cpp/build/windows/vs2010/OpenZWave.vcxproj, cpp/build/windows/vs2010/OpenZWave.vcxproj.filters
These files were missing from the Windows build, causing linker errors to occur
/CC @Fishwaldo
=> Added missing `ManufacturerProprietary` files to Windows builds

config/homeseer/hs-ws100plus.xml
Tested via Open-zwave-control-panel on a live switch. All 3 defined
states work as expected.
Reference for these config parameters / values is here:
http://products.z-wavealliance.org/products/1731/configs
Also verified with HomeSeer Inc via support email.
=> Added LED policy config settings to HomeSeer HS-WS100+ switch

config/gocontrol/GC-TBZ48L.xml, config/linear/GC-TBZ48.xml, config/linear/GC-TBZ48L.xml, config/manufacturer_specific.xml, distfiles.mk
this device description provides configuration parameters for http://products.z-wavealliance.org/products/2370/ and http://products.z-wavealliance.org/products/1286
The second one does not have any information on the config parameters but it seems that most of the config parameters work same way
For most part, they are similar but some of the parts are little different. The changes on distfile.mk were results of `make dist-update`.
Thanks!
=> add gocontrol/linear thermostats

config/leviton/dz15s.xml, config/manufacturer_specific.xml, distfiles.mk
Add support for the Leviton Decora DZ15S Switch.  This includes
configuration item 7, which allows changing the LED at the base of the
switch to Status Mode, Locator Mode, or Off.  This been tested on the
hardware, and basic functionality as well as the configuration option
work correctly.
=> Add Leviton DZ15S Switch

config/manufacturer_specific.xml
This is the device: http://products.z-wavealliance.org/products/1959. The config params and association groups match with https://github.com/OpenZWave/open-zwave/blob/master/config/leviton/dz15s.xml so just using that
=> add leviton dzpa1

config/aeotec/zw100.xml
I have only took care of two erroneous parameters. There is probably more to do (see #1240).
=> Fixed off-limit default values for Aeotec ZW100.

config/manufacturer_specific.xml
Hank released a revision of the DWS01 door/window sensor.  No changes from the original one configuration wise but the type ID was different so OpenZWave didn't detect the config params automatically.  Added an entry in manufacturer_specific.xml to point this new type id to the same config file as the old DWS01 and everything appears peachy.
=> Include new Hank DWS01 revision..

config/manufacturer_specific.xml
Ecolink Door/Window with Zwave plus has the type=0004 and id=0002
This should allow openzwave to identify this sensor now.
=> Add support for Ecolink Door/Window ZWave+

config/manufacturer_specific.xml
The model I purchased recently had a different "id" value. This may be the US model if the "0600" id is for EU?
=> Adding variant of Yale YRD446

config/manufacturer_specific.xml
This device sometimes uses Type 0004 ID 0002.  This change was tested with HASS and confirmed to work properly
See http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/138
Link to the product on Amazon: https://www.amazon.com/gp/product/B01N5HB4U5/
=> Add Ecolink DW-ZWAVE2.5-ECO

config/manufacturer_specific.xml
Have 2 2GIG CT100 Plus Thermostats, but each have a different id (`0100` and `0001`), so updating to add the second.
=> Added new device ID; 2GIG CT100 Plus Thermostat

config/manufacturer_specific.xml
Add the Linear GD00Z-4 Garage Door Opener Remote Controller product to the manufacturer_specific.xml.
The values for type and id were observed using HomeAssistant with the Dev branch of open-zwave.
Cheers,
=> Add Linear GD00Z-4 Garage Door Opener Remote

cpp/src/command_classes/SwitchBinary.cpp, cpp/src/command_classes/SwitchBinary.h
Here's a first draft to support Binary Switch v2 (#1263). As I'm not too familiar with C++ and the OZW architecture, please have a look if I didn't forget anything or if more changes are neccessary. Also, I'm gonna squash the commits later when I have VisualStudio back, I'm too dumb for vim.
Regarding the requested features:
> Target Value from a Report message (4.12.3) - This would address #1261 if thats a v2 implementation
=> I exposed the target state as read-only. Is this ok?
> update Value::VerifyRefreshedValue to not have to do another GET if we received a target value.
=> no clue what to do here
=> Support Binary switch v2

cpp/src/command_classes/MultiInstance.cpp
It happened sometimes that the MultiChannelCapabilityReport for the same endpoint came in more than once. In this case a additional Instance for the same endpoint gets created. By checking if there is a instance for the given endpoint and CommandClass, this can be prevented.
I'm not sure if this also needs to go into the "all endpoints are the same" part?
zwcfg_0xXXXXXXX.xml with this error
```
<CommandClass id="38" name="COMMAND_CLASS_SWITCH_MULTILEVEL" version="3" issecured="true">
<Instance index="1" endpoint="1" />
<Instance index="2" endpoint="1" />
<Instance index="3" endpoint="2" />
```
Log of 2 MultiChannelCapabilityReport for endpoint 1
[multiinstance_for_endpoint.txt](https://github.com/OpenZWave/open-zwave/files/1200414/multiinstance_for_endpoint.txt)
=> Fix MultiInstance handling for CapabilityReport

cpp/src/Driver.cpp
The `m_currentControllerCommand->m_controllerStateChanged` was only reset when there is a callback, but all the ControllerCommands called by the manager don't supply a callback method (except the one for custom Controller Commands, where a Callback could be given).
This caused the DriverThreadProc loop to always read that command (e.g. AddNode) from the loop, go into the `WriteNextMsg` and run into the if( `m_currentControllerCommand->m_controllerStateChanged` ), doing nothing and return again and again and again... -> high cpu load because of endless loop until canceled or finished.
=> Fix high CPU load when adding nodes

cpp/src/Driver.cpp
As requested by @Fishwaldo  #1272 as PR
In networks with heavy load, especially with lots of security frames (`NONCE_GET`) Controller Command could hang and never return.
The reason for this:
Receiving a `NONCE_GET` OZW handles this quite low level, below all queues. When a `NONCE_GET` is received, a `NONCE_Report` is immediately sent. If this `NONCE_Report` fails because of e.g. a `CAN`, then it is re-transmitted on queue level. But instead of a extra queue for this, the re-transmission gets done in `Driver::WriteMsg()`. The way this is done (as far as i understand it): If there is a nonce that needs to be re-transmitted, send it instead of the actual frame. The actual frame is then lost. While this is not that big of a deal for a `SWITCH_BINARY_SET` or something like this, if the …
=> Workaround for silently dropped frames

config/ge/receptacle.xml
Per [this document](http://www.ezzwave.com/advanced-operation/) the GE 12721 Smart Outlet supports an additional parameter to turn the LED light all the way off. This adds that support and clarifies the other options.
=> Allow LED on GE 12721 Smart Outlet to be turned off

config/aeotec/zw100.xml
The configuration 81 affects only motion (PIR), not motion or vibration (from engineering sheet and confirmed by observation).
=> Fixed 81 description

config/philio/pst02.xml
The multisensor quad PST02 need the same mapping than PSM02 to differentiate the event from motion sensor, door/window sensor and tamper sensor.
=> Update pst02.xml for sensor map.

config/manufacturer_specific.xml, config/vision/zd2105us5.xml, distfiles.mk
This PR adds the Vision ZD2105US-5 recessed door/window sensor.
https://products.z-wavealliance.org/products/1727
I need help figuring out what we need to add to the config file for it. According to the [manual](https://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/1727/ZD%202105-5_V1-20160329.pdf) there are no config settings. It also says it can be associated with 5 nodes. I'm also not 100% sure yet what it does with the Basic CC so I don't know if it should be set as report. Should the config file have just the Association CC?
=> add vision ZD2105US-5 recessed door/window sensor

config/ge/12719-plugin-switch.xml, config/manufacturer_specific.xml, distfiles.mk
GE 14293 is called "14292-1" on the box and "14293" in Z-Wave and on the manual (which lists itself as being for both 14292 and 14293). I went with 14293. Regardless, the product is identical and is just an ID update.
GE 12719 is a simple semi-smart plug in toggle switch. No settings to speak of (verified via Jasco and the Z-Wave device DB).
`make dist-update` seems to have added some other recent changes to the `distfiles.mk` file as well. I left them in there, suspecting a previous commit missed that step.
=> Added GE 12719 and GE 14293

config/vision/zd2105us5.xml
This sensor uses BASIC SET as a report. The manual also documents it.
This sensor reports a binary sensor but, according to my tests, it doesn't respond to requests. The manual does not document to support of a binary sensor. This commit removes the binary sensor.
For more details the manual is here: https://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/1727/ZD%202105-5_V1-20160329.pdf
=> Vision ZD2105US-5 basic as report & remove binary sensor

config/aeotec/zw080.xml
Add a missing parameter to turn on/off the alarm sound via pressing the Action Button.
Documentation : https://aeotec.freshdesk.com/helpdesk/attachments/6052990312
=> Add missing parameter to Aeotec Siren Gen5

config/2gig/ct80.xml, config/manufacturer_specific.xml, distfiles.mk
I copied `config/ct50e.xml` and updated the comment. This change fixed handling of the `ThermostatSetpointCmd_Get` command for two of the four climate devices reported by the thermostat.
I can just re-use the existing `config/cte50e.xml` file (pointing to that in `manufacturer_specific.xml`) if that's preferred.
=> Add new device: 2Gig (Radio Thermostat) CT80

config/cooper/RFWC5.xml, config/manufacturer_specific.xml, cpp/src/command_classes/Indicator.cpp
Some devices (like multi button scene controllers Cooper RFWC5/RFWDC) utilize more than 1 bit to report status of their indicators. The fix makes the received data to be treated properly as a value in 0-255 range.
=> Fix handling Indicator report data

cpp/src/Driver.cpp, cpp/src/Msg.cpp, cpp/src/platform/Stream.cpp
Sometimes openzwave based binary would crash with a segmentation fault. I ran with valgrind and it showed some warnings on uninitialized members. I believe the segfault was triggered because a LogData in Stream.cpp is logging data from a buffer but the calculated buffer position is wrong, leading to read before the buffer starts:
==7364== Thread 4:
==7364== Invalid read of size 1
==7364==    at 0x289080: OpenZWave::Stream::LogData(unsigned char*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (Stream.cpp:228)
==7364==    by 0x288D96: OpenZWave::Stream::Put(unsigned char*, unsigned int) (Stream.cpp:159)
==7364==    by 0x28CC00: OpenZWave::SerialControllerImpl::Read() (SerialControllerImpl.cpp:327)
==7364==    by 0x28C620: …
=> Fix valgrind memory warnings and potential cause for a segmentation fault.

config/manufacturer_specific.xml
Added this device to my home and noticed that it was displaying as unknown - checked manufacturer_specific.xml and noticed this duplicate entry. Cleaned up the duplicate entry and renamed the device to follow the naming convention for other Leviton devices.
=> Cleanup entry for Leviton DZPA1-2BW

cpp/src/command_classes/ThermostatSetpoint.cpp, cpp/src/command_classes/ThermostatSetpoint.h
Separate PR for Thermostat Setpoint V3
Adds new setpoint types and `Capabilites` Command to discover min / max of the setpoint types.
Also adds new configuration parameter `typeInterpretation` because there is a interpretations Issue with this command class.
>It has been found that early implementations of this Command Class specification apply two non-
interoperable interpretations of the bit mask advertising the support for specific Setpoint Types.
As a consequence, one may find thermostat products and controller products in the marketplace which
implement either of the two bit mask interpretations found in Table 106. The notation x.y indicates Bit
Mask byte x, bit y.
see #1341 for more details
=> Thermostat setpoint v3

config/BeNext/EnergySwitch.xml, config/BeNext/Molite.xml, config/BeNext/TagReader.xml, config/BeNext/TagReader500.xml, config/act/zir010.xml, config/aeotec/zw100.xml, config/everspring/ad147.xml, config/everspring/an145.xml, config/everspring/an158.xml, config/everspring/sf812.xml, config/everspring/sp103.xml, config/merten/507801.xml, config/merten/50x5xx.xml, config/zipato/MiniKeypad.xml, config/zwave.me/ZME_05461.xml, config/zwave.me/ZME_06433.xml, cpp/src/Node.cpp, cpp/src/Node.h
Resolves #1397 
The Pepper1 DB no longer exists.  This removes a bunch of broken links from various configuration files.  And removes support for the Pepper1 metadata item (which was used by one product only).
=> Removing references to pepper1

config/logicsoft/ZHC5010.xml
I have four of these nodes working through v1.4 and v1.5 for node-red and domoticz and phyton.
To assist first-time users with these units, it is important that:
1) ZHC5010 Configuration which can enable/disable direct control over relay can be controlled and
2) ZHC5010 responds fast by default.
To do this, XML config file must have
1) MultiInstance CC set to mapping="all" (Yes, redundant but description enables users to change if instance0 is not needed (No direct Relay control)
2) Disable CC SWITCH_ALL. It seem not supported in v2.03 firmware (and earlier) and it cause OZW to timeout on startup.
3) Remove default Controller associations to any other CC than BASIC_REPORT, which is needed by Domoticz/Node-Red to learn of button-pres (which on/offs the internal switch).
If Controller is …
=> Updated ZHC5010 configuration

config/fibaro/fgd212.xml
Parameters 53 and 59 are mixed up.
https://manuals.fibaro.com/content/manuals/en/FGD-212/FGD-212-EN-T-v1.3.pdf
This was fixed in f342283 but seems to have been (accidently) reverted in 89cee9a.
=> Fix Fibaro Dimmer 2 FGD212 Parameters

cpp/src/command_classes/Clock.cpp
This should fix #843 
When updating, say, Hour and Minute, you had to wait for the change report to return before updating the next field.
Example log:
```
2018/01/09 19:48:30 ZWave: Node 7: Polling 2 values.
2018/01/09 19:48:30 Time: 4:16
2018-01-09 19:48:30.279 Info, Node007, Value::Set - COMMAND_CLASS_CLOCK - Hour - 1 - 1 - 5
2018-01-09 19:48:30.279 Info, Node007, Value::Set - COMMAND_CLASS_CLOCK - Minute - 2 - 1 - 10
2018/01/09 19:48:30 ZWave: Node 7 changed: User 0x81.1.1: Hour: 5 
2018-01-09 19:48:30.280 Info, Node007, Sending (Send) message (Callback ID=0x21, Expected Reply=0x13) - ClockCmd_Set (Node=7): 0x01, 0x0b, 0x00, 0x13, 0x07, 0x04, 0x81, 0x04, 0x65, 0x10, 0x25, 0x21, 0x10
2018/01/09 19:48:30 ZWave: Node 7 changed: User 0x81.1.2: Minute: 10 
2018-01-09 19:48:31.540 Info, …
```
=> Refresh clock values upon change

config/assa_abloy/ConexisL1.xml, config/assa_abloy/KeyfreeConnected-plus.xml
I noticed the setting parameter for Auto Relock had the  wrong values on these two locks this PR fixes that,
Instead of 'off' being '255' its actually 'on'
https://products.z-wavealliance.org/products/2535/configs
https://products.z-wavealliance.org/products/2743/configs
Fix Auto relock setting on Conexis L1 and Keyfree Connected plus locks
=> Fix Auto relock setting on Conexis L1 and Keyfree Connected plus locks

config/manufacturer_specific.xml
Mcohome appareantly released a different id-version of the same product. 
Tested it with the new product type and id, and used the original "mcohome/mhs412.xml" 
as the lifeline switch is still present in this version.
It now performs perfectly.
Product type="4121" id="1302" 
No idea as for naming convention but i named it version B  as its a black one + info on the box says "MH-S412-EU B" (switch just says MH-S412-EU on the back)
=> Added new version of the MCO home MH-S412

config/popp/009402.xml
Reverting max_association
Original config file was correct and is still correct according to the manual. 
Source: http://manuals-backend.z-wave.info/make.php?lang=en&sku=pope009402&type=popp
Have tested with more than 4 association in group 2 without problem
=> Reverting max_associations to correct values

config/hank/hkzw-fld01.xml
After the explanation in be3469343c672e38146e1f3b83705af050244586 the comment is not needed.
=> Comment not needed

cpp/src/Manager.cpp, cpp/src/Manager.h
Right now, it is not possible to remove a watcher from from the callback itself, because this causes the iterator in `NotifyWatchers` to be invalidated. In other words, there are scenario's in which it is unsafe to call `RemoveWatcher`.
As an example, it is currently not possible to write code like below without causing a fatal crash (simplified example):
```cpp
void OnNotification ( Notification const* _notification, void* _context ) {
// Do something we only need to do once
// ...
// We no longer need notifications, remove this watcher
Manager::Get()->RemoveWatcher( OnNotification, NULL );
}
Manager::Get()->AddWatcher( OnNotification, NULL );
```
In this simplified example it is of course a bit silly to want to remove the watcher, but in a more complex application it may make sense to …
=> Allow RemoveWatcher to be called from a watcher callback

cpp/build/Makefile, cpp/build/support.mk, cpp/examples/MinOZW/Makefile, cpp/hidapi/libusb/hid.c, cpp/src/platform/unix/EventImpl.cpp, cpp/src/platform/unix/SerialControllerImpl.cpp
These are the changes I had to make to get open-zwave working (with domoticz) under NetBSD/amd64-current. There's just a very small handful:
- help the build system find libusb-1.0, so it can build the USB bits
- correct for a command line option difference in the fmt(1) utility
- drop a call to an unimplemented phtreads function (the call just sets what's default, anyway, so nfc)
- open the USB serial device O_NONBLOCK, so the call to open(2) doesn't hang
With these changes, domoticz happily uses my Aeotec and Z-Wave.Me USB sticks.
=> Initial NetBSD port

cpp/build/Makefile
Reverts OpenZWave/open-zwave#1495 as it breaks packaging. See #1508
=> Revert "Fix issue with $pkgconfigdir not being used as an absolute path"

config/manufacturer_specific.xml
One of my FGS223 double relay switches had an ID of 2000 instead of the "3000" that the others had. This just adds the "2000" id in there as a valid ID for this model.
=> add FGS223 Double Relay with a separate ID to manufacturer_specific.xml

config/inovelli/nzw31.xml, config/manufacturer_specific.xml
Based on Inovelli-provided SmartThings device handler, and tested against a hardware NZW31 switch.
=> Add support for Inovelli NZW31 switch config, add additional device IDs

config/homeseer/hs-wd100plus.xml
The changes allow the parameters to be set to their full allowable range of values, as specified in the documentation:
https://homeseer.com/wp-content/uploads/2018/06/HS-WD100-Manual-6a.pdf
The documentation specifies the size of parameters 7 and 9 as 1 byte, however defining them as bytes prevented OZW from updating the values: the values would always reset to 1, regardless of the supplied value. Using short works.
=> Fix parameter size and allowed values for HS-WD100+

cpp/hidapi/libusb/hid.c
When I created the (since merged) pull request #1492 to make open-zwave build on NetBSD, I accidentally omitted to enclose one platform specific change in an ifdef. @ryanwinter points out that this breaks the build on FreeBSD.  This change corrects the omission.
=> Add missing #ifdef __NetBSD__ for a platform specific cast

cpp/src/command_classes/DoorLockLogging.cpp
=> Fix compilation error in regards to -Werror=restrict

cpp/src/platform/unix/SerialControllerImpl.cpp, cpp/src/platform/unix/SerialControllerImpl.h
The current version of OpenZWave hangs on macOS when the interface is being closed. Add event polling to fix this.
=> Fix hangs during Manager::Destroy calls

config/zooz/zen22v2.xml
The documentation that came with my zooz zen22 version 2 light indicates this option should exist. I've added it on my own setup and it is working as described. Quote from the documentation:
> **Ramp Rate Control**
> Parameter 4: Choose from 2 ramp rate options (fade-in / fade-out effect for on / off operation)
> Values: 0 - light turns on to 100% brightness within 2 seconds, turns off within 4 seconds (default); 1 - light turns on to 100% brightness instantly, turns off within 1 second
> Size: 1 byte dec.
=> Added ramp rate control option to zen22v2.xml

cpp/build/windows/mingw-w64/Makefile, cpp/src/Defs.h, cpp/src/platform/windows/FileOpsImpl.cpp, cpp/src/platform/windows/LogImpl.cpp
1. cpp/src/build/windows/mingw-w64/Makefile - added a Makefile with support for MinGW-W64.
2. cpp/src/Defs.h:38 - added support for MinGW-W64.
3. cpp/src/platform/windows/LogImpl.cpp:84 - switched two values in the initializer list to fix a -Wreorder warning.
4. cpp/src/platform/windows/FileOpsImpl.cpp:62 - changed "int32 ftype" to "uint32 ftype" to match the (unsigned) DWORD return value of the "GetFileAttributesA" function to fix a -Wsign-compare warning.
=> Added support for MinGW-W64

cpp/build/winRT/vs2015/OpenZWave.vcxproj, cpp/build/windows/vs2010/OpenZWave.vcxproj
This change allows you to build the project with newer versions of Visual Studio.
Without this, VS2017 will complain that the v10.0 C++ toolset isn't installed. With this it'll pick v14.0 or 14.1 (depending on which are installed), and will support future versions as well.
Also added the `Localization.cpp`/`.h`. Without these, linking the generated static libs will fail.
=> Allow build with newer Visual Studio

cpp/src/command_classes/SensorMultilevel.cpp, cpp/src/command_classes/SensorMultilevel.h
My first pull request here so let me know if I'm doing something wrong. Added 37 Multilevel Sensor Types with corresponding scales according to the Z-Wave specification for Multilevel Sensor Command Class. 
http://zwavepublic.com/sites/default/files/command_class_specs_2017A/SDS13812-2%20Multilevel%20Sensor%20Command%20Class%2C%20list%20of%20assigned%20Multilevel%20Sensor%20types%20and%20scales.pdf
=> added Multilevel Sensor types and scales for version 6-11

config/manufacturer_specific.xml
This seems to be an updated version of the one with ID 5436.
=> Added another version of the GC-TBZ48 with ID 5437.

cpp/src/Driver.cpp, cpp/src/Driver.h, cpp/src/Group.h, cpp/src/Manager.cpp, cpp/src/Manager.h, cpp/src/Node.cpp, cpp/src/Node.h
(Change to Dev branch for pull request #1584)
Group in ZWave can have multi instance availability or not.
This is correctly programmed in Group.h/Group.cpp but it is not available to end user (user of OpenZWave library).
I have created a patch, that publishesh Group.h `IsMultiInstance` to Manager.h:
```c++
/**
* \brief Returns true is group supports multi instance.
* \param _homeId The Home ID of the Z-Wave controller that manages the node.
* \param _nodeId The ID of the node whose associations we are interested in.
* \param _groupIdx one-based index of the group (because Z-Wave product manuals use one-based group numbering).
* \return True if group supports multi instance.
* \see GetNumGroups, AddAssociation, RemoveAssociation, GetAssociations
*/
bool IsMultiInstance( uint32 const …
```
=> Published IsMultiInstance from Group to Manager

cpp/src/Driver.cpp
Also there's no reason to continue the loop once the node has been found and removed.
Fixes #1609 / https://github.com/OpenZWave/openzwave-dotnet-uwp/issues/22
=> Fixes an access violation on the NextSibling after a child has been removed

config/manufacturer_specific.xml
Hi. Ive got a Yale YKFCON lock equipped with the new (dark blue) Zwave+/S2 module and it's device type and id doesnt match the config file, so i amended it.
Sorry if not following the process, im a complete github noob.
=> Adding device id and type for YKFCON with ZW+/S2

cpp/build/Makefile, cpp/build/support.mk, cpp/examples/MinOZW/Makefile
I attempted to build OZW on macOS Mojave (10.14) but was blocked by a couple of issues with the **Darwin**-specific build process:
- Xcode's **make** no longer supports the `i386` architecture. I've removed these build targets from the OZW library as well as the MinOZW example application
- The build failed on several unused private fields defined within the various Value classes. The `-Wunused-private-field` gcc flag was being implicitly set somewhere (I couldn't identify where), but I was able to add an additional flag to ignore such errors.
I can confirm that, with these changes, OZW can now be built and installed on macOS 10.14 with a simple `make && sudo make install`.
=> Fix broken build process for macOS

cpp/src/command_classes/SwitchMultilevel.cpp
Requested in https://github.com/OpenZWave/open-zwave/issues/1321 
Here's my take, as the changes are pretty similar to binary switch v2. Compiled without errors on Windows/VS2017.
Sadly, I still have to pass when it comes to changing Value::VerifyRefreshedValue.
=> Support switch multilevel v4

cpp/src/Group.cpp, cpp/src/Group.h, cpp/src/value_classes/ValueBool.cpp, cpp/src/value_classes/ValueBool.h, cpp/src/value_classes/ValueByte.cpp, cpp/src/value_classes/ValueByte.h, cpp/src/value_classes/ValueInt.cpp, cpp/src/value_classes/ValueInt.h, cpp/src/value_classes/ValueList.cpp, cpp/src/value_classes/ValueList.h, cpp/src/value_classes/ValueShort.cpp, cpp/src/value_classes/ValueShort.h
A number of unused variables cause compilation errors in FreeBSD 11.2.
=> Remove unused variables causing compilation errors on FreeBSD

config/homeseer/hs-fc200plus.xml, config/manufacturer_specific.xml, distfiles.mk
New config xml file for the HomeSeer FC200+ Fan Controller: https://shop.homeseer.com/collections/lighting/products/homeseer-hs-fc200-z-wave-plus-fan-controller
Includes the central scene command class. This was initially grabbed from the Home Assistant help page for device-specific configuration: https://www.home-assistant.io/docs/z-wave/device-specific/#homeseer-switches. The scene data that is shown in the OZW log matches the "Top button ID: 1, Bottom ID: 2" in the HomeAssistant docs.
The config parameter help text is copied nearly verbatim from the HS user manual, so it does differ slightly from the other HS switches.
=> Config file for HomeSeer FC200+ Fan Controller

config/thermofloor/heatit033.xml
- Fixed parameter 12 from short (not working) to byte. 
- Brightness settings changed from short to byte.
- Association Group Internal relay changed from 2 to 5.
- Association Group Multilevel sensor reports - Internal sensor changed from 3 to 2.
- Association Group Multilevel sensor reports - External sensor changed from 4 to 3.
- Association Group Multilevel sensor reports - Floor sensor changed from 5 to 4.
This product is released with non Z-Wave alliance certificated firmware (2.6) (sale stop until final approved version is released) All Z-TRM2 thermostats will need to update firmware in the future and new ones will be shipped with fw2.11 or later.
=> Heatit Z-TRM2 Update for firmware v2.11

cpp/src/command_classes/ZWavePlusInfo.cpp, cpp/src/command_classes/ZWavePlusInfo.h
The correct command class name for z-wave plus, according to [this wiki](http://wiki.micasaverde.com/index.php/ZWave_Command_Classes) and other official sources, is `COMMAND_CLASS_ZWAVEPLUS_INFO` instead of `COMMAND_CLASS_ZWAVE_PLUS_INFO`.
I updated all of the instances where I found this in the repo.
=> Fixed Z wave plus command class name

config/manufacturer_specific.xml
Recently installed YRD216 and YRD210 in same network, discovered the YRD216 incorrectly named YRD210 in manufacturer_specific.xml. The YRD210 with id aa00 was not in manufacturer_specific.xml
=> Update Assa Abloy in manufacturer_specific.xml

config/ge/28169-plugin-switch.xml, config/manufacturer_specific.xml, distfiles.mk
These two commits add support for GE 29169 switch and GE 12718 Dimmer products.  The switch was new, but the dimmer is identical from a z-wave configuration perspective to the ge-dimmer-module.xml, so I have just referenced it here.  I have both devices available on my network for testing and questions.
=> Add support for GE 29169 and 12718 Plug-in Products

config/linear/GC-TBZ48.xml
Add missing configuration parameter 23.   This parameter changes what information is reported automatically reported by the thermostat upon a change in its state.  This will allow a fix of the known issue of the thermostat by default not reporting a change in its operating state and the start and end of a call for heat/cool.
Add Association Groups.
=> Configuration update for Linear GoControl GC-TBZ48

config/manufacturer_specific.xml
First PR, so be gentle.
Added one line to add type "0002" of the Oomi Multisensor unit. I have this unit myself.
Two commits because of indentation error.
=> Add Oomi multisensor european version

config/qubino/ZMNHLDx.xml
Fixes #1319
Without this you can't set a temperature for the thermostat.
=> Fix Qubin PWM Thermostat ThermostatSetpoint

config/manufacturer_specific.xml
It seems that Assa Abloy (Yale) has YRD220's with an ID of aa00, in addition to 0000. I have added this change to my own xml file and it works with my YRD220.
=> Add YRD220 with id=aa00

ChangeLog, config/idlock/idlock150.xml, config/manufacturer_specific.xml, distfiles.mk
Adding IDLock 150 support.
Manufacturer doc is here: https://idlock.no/wp-content/uploads/2018/08/IDLock150_ZWave_UserManual_v2.1.pdf
=> Add SmartLock Idlock 150

cpp/src/Manager.cpp
Incorporate jmattioni's changes to fix #792.
=> Cleans up static variables during Manager destruction.

config/manufacturer_specific.xml
Those new power plugs are just the same as the old ones in terms of looks and packaging, but show up with a different type and ID.
=> Adds a new Neo Coolcam Power plug type and ID

config/manufacturer_specific.xml
New product type and id for 2GIG CT101. Confirmed full functionality/testing with actual hardware. While OpenHAB reports this device as a CT100, it does have a humidity sensor which makes it a CT101. This one of the Iris models but strangely not listed yet.
=> Add new product type and id for the 2GIG CT101

config/zooz/zen27.xml
The [Zooz Zen27  S2 Dimmer Switch documentation](https://cdn.shopify.com/s/files/1/0218/7704/files/zooz-z-wave-plus-s2-dimmer-switch-zen27-manual.pdf?7399472298769089473) says that parameter 9, 10, and 11 are 1 byte. The XML config for this device is setting it to a 2-byte value (size=2). It's also a short instead of byte.
I also added some missing descriptions.
`make xmltest` passes with flying colors and device responds correctly once modifications are made.
=> update Zooz Zen27 S2 Dimmer Switch ramp rate, min/max brightness parameters

config/manufacturer_specific.xml, config/thermofloor/heatit056.xml
Heatit Z-TRM2 is replaced with Z-TRM2fx. Z-TRM2 is withdrawn from marked and owners can send it back to Thermofloor to get a new Z-TRM2fx replacement.
Since both products have different config but share the same product type/id The XML files should be replaced with config for FX version as this is the only Z-TRM2 product in sale.
=> Add support for Heatit Z-TRM2fx

config/manufacturer_specific.xml, distfiles.mk
The 14299 can use the same config as the 14294. Per the Z-Wave alliance, the configuration commands are identical:
* [In-Wall Smart 1000W Dimmer (14299/ZW3006)](https://products.z-wavealliance.org/products/2168/configs)
* [In-Wall Smart Dimmer (14294/ZW3005)](https://products.z-wavealliance.org/products/2105/configs)
Ran `make xmltest` without error.
Ran `make distupdate`, some missed files from earlier commits were added.
=> Add GE (Jasco) 14299 In-Wall 1000W Smart Dimmer.

config/leviton/vrcz4.xml, config/manufacturer_specific.xml
The Leviton VRCZ4 uses association groups 1-4 to set devices controlled (with basic set commands) with buttons 1-4.  It doesn't make sense to auto-add the controller to group 1 for this device.  Added a custom config to allow disabling that auto association, and give a slightly more descriptive name for those groups.
=> Add custom config for Leviton VRCZ4

config/aeotec/zwa003.xml
Added support for the 4 buttons.
Source: https://products.z-wavealliance.org/products/2817
https://aeotec.freshdesk.com/support/solutions/articles/6000184697-nanomote-quad-technical-specifications-
https://aeotec.freshdesk.com/support/solutions/articles/6000184696-nanomote-quad-user-guide-
Added support for Config value 41--Enable send central scene notification.
source: https://products.z-wavealliance.org/Products/2817/XML
=> Updated support for Aeotec NanoMote Quad

config/fibaro/fgr223.xml
Typo fix for Fibaro Roller Shutter 3
Fixed type of parameter #41. Proper value is "byte"
Due to wrong type parameter was inactive and triggering scenes by S2 not possible.
=> Fibaro Roller Shutter 3 fix for scene triggering by S2 - fgr232.xml #41 type=byte

config/aeotec/zw056.xml
Updated zw056.xml to make "Play Ringtone" write_only="true". Get commands after set commands were causing timeouts. The timeouts eventually trigger the node to be marked as dead.
[zw056.log](https://github.com/OpenZWave/open-zwave/files/2770497/zw056.log)
=> Set "Play Ringtone" to write_only in config/aeotec/zw056.xml

config/manufacturer_specific.xml, config/zwp/PA-100.xml, distfiles.mk
Add support for zwaveproducts.com Plug-In Appliance Module, ZL-PA-100 https://www.zwaveproducts.com/shop/z-wave-lighting/z-wave-plugin-modules/zlink-products-plug-in-appliance-module-zl-pa-100
=> Add ZWP PA-100 support

cpp/examples/MinOZW/Main.cpp, cpp/src/Driver.cpp, cpp/src/Driver.h, cpp/src/Manager.cpp, cpp/src/Manager.h
After testing and logging the controller response, to the "enable extended status" serial command, this method should return true if this status is supported.
MinOZW updated to print this status.
Tested on a UZB1 with recent firmware, not tested on a controller which lacks the capability, because I do not have one...
=> Implement Manager::HasExtendedTxStatus

cpp/examples/MinOZW/Main.cpp, cpp/src/Manager.cpp
This would help me Without this change, all Dev logs start with "OpenZwave Version 1.5.3770 Starting Up" (based on tag info in git) so I am not sure if I'm linking agains a build that was based on the latest commit. With this change it prints "OpenZwave Version V1.5-3770-gd11ab62b-dirty Starting Up".
=> replace getVersionAsString() with getVersionLongAsString()

cpp/src/CompatOptionManager.cpp
Build on Mac with gmake -j 4 CXX=c++-8 LD=C++-8 revealed these issues.
=> Fix GCC 8 build + return in GetXMLTagName

cpp/src/Defs.h, cpp/src/command_classes/TimeParameters.cpp, cpp/src/platform/unix/LogImpl.cpp, cpp/src/platform/unix/TimeStampImpl.cpp
#1762 
Tested on Mac llvm + gcc, not tested on Windows.
=> Replace localtime with localtime_r for thread safety

cpp/src/Driver.cpp
Some code used _data[3] in to log Node ID,
but not all serial data frames report back node number.
Use GetNodeNumber() instead.
Without this bugfix you'll see log lines like this:
```
Info, contrlr, Received reply to FUNC_ID_ZW_GET_VERSION:
Info, contrlr,     Static Controller library, version Z-Wave 4.61
Detail, Node045,   Expected reply was received
```
The 'Node045' part is incorrect. After this patch:
```
Info, contrlr, Received reply to FUNC_ID_ZW_GET_VERSION:
Info, contrlr,     Static Controller library, version Z-Wave 4.61
Detail, contrlr,   Expected reply was received
```
=> Fix bogus Node IDs in logging

cpp/src/Node.cpp
A crash was triggered here. Seems the only place where this was not checked
=> Fixed crash when AddCommandClass returned NULL

config/manufacturer_specific.xml, config/schlage/BE468ZP.xml, distfiles.mk
Add support for the Schlage BE468ZP, which is now available on the market, and similar to the BE469ZP, but without the built-in alarm.  (It also has a white keypad instead of blue.)
https://products.z-wavealliance.org/products/3028
=> Add config for Schlage BE468ZP Connect Smart Deadbolt

config/manufacturer_specific.xml
I have the Kwikset SmartCode 914 z-wave plus model and can confirm this is the correct device id/type. Requesting it added to the device list for proper identification.
=> Added Kwikset SmartCode 914 device id/type

cpp/src/Node.cpp
Fixes issue #1414
The most up-to-date specification of the NIF (that I could find) is in SDS13781 "Z-Wave Application Command Class Specification.pdf" chapter "3.4 Node Information Frame". However, it does not explain the 3rd byte, it still lists that byte as "Reserved". By crafting packets and decoding them with Zniffer I could determine the speed bits, which encode the "speed extension". PC Controller by Silabs also lists this property as "speed extension".
=> Decode "speed extension" in protocol field to detect 100 kbit devices

config/manufacturer_specific.xml, config/zooz/zse29.xml
Adds support for the ZSE29 Outdoor Motion Sensor from Zooz. The device does not
use Z-Wave for configuration. There are manual knobs on the device to configure
the device.
Z-Wave Product Catalog page for reference:
https://products.z-wavealliance.org/products/3081
Tested this with an actual device using OpenZWave through Home Assistant.
Resolves #1809.
=> Add support for Zooz ZSE29

cpp/src/platform/unix/ThreadImpl.cpp
The parameter list for pthread_setname_np() is slightly different in the NetBSD implementation.
=> Set thread names on NetBSD

config/device_classes.xml, cpp/src/Node.cpp
DeviceTypes added, and tested with Neo Wall Switch (2 channels), which has User Icon aka "Device Type"  0x1d02 which was not in previous version of device_classes.xml. OZW_Log:
```
2019-05-24 11:24:54.897 Info, Node004,   Zwave+ Device Type  (0x1d02) - On/Off Wall Switch, 2 buttons. Mandatory Command Classes:
2019-05-24 11:24:54.897 Info, Node004,     NONE
```
Generic and Specific types have been added as well, for example:
```
<Specific key="0x01" label="Sound Switch" command_classes="0x55,0x59,0x5a,0x5e,0x6c,0x72,0x73,0x79,0x85,0x86,0x9f"/>
```
Those have not been tested, I don't have any test device in those categories.
=> Update device_classes.xml and fix logging bugs

cpp/src/Driver.cpp
Experienced a crash here. node was NULL. This is checked everywhere in this function except on this location
=> Fixes crash when node = NULL

cpp/src/Node.h
Solves the following compile issue under travis:
> /home/travis/build/open-zwave-read-only/cpp/src/Node.h:566:32: error: ‘std::shared_ptr’ has not been declared
=> Added missing include for shared_ptr

cpp/src/Utils.cpp, cpp/src/Utils.h
Currently it is not declared as 'const' and this is causing compilation issues for applications that also introduces their own localtime_r implementation that is using the arguments as declared in the spec
=> localtime_r first argument should be const

cpp/src/Localization.cpp
Solves Help text of "Seismic Intensity" is wrong: "Tank Capacity Sensor Value".
https://github.com/OpenZWave/open-zwave/issues/1887
Corrects help text of all IDs > decimal 9.
Requires node refresh or delete ozwcache to (re)write cached Help text.
=> Fix Help text localization index strtol (change base 16 to 10)

config/aeotec/zwa005.xml, config/manufacturer_specific.xml
The Aeotec ZWA005 is available here in :australia:, this change adds the appropriate entries to its configuration.
=> Add Australia/New Zealand to Aeotec ZWA005

config/aeotec/dsa03202.xml, cpp/build/testconfigversions.cfg
Add <GetSupported>false because device does not support "Get"
Add label="As-Last-Set" to work around the issue that applications tend to revert to display "group mode" while device is actually in scene mode.
=> Improve Aeotec Minimote config file

config/manufacturer_specific.xml
The GoControl LB30Z is functionally the same as the LB60Z, just in a different form factor. Adding the specific device (which I own and validated) for support.
=> Added GoControl LB30Z-1 BR30 bulb

cpp/src/Driver.cpp
Second crash observed when Log has "Dropping Notification as ValueID does not exist"
=> Fix sigsegv after refresh node. Fix crash when ozwcache holds data to deleted nodes

cpp/src/command_classes/MultiCmd.cpp
This stops creating bogus data, as reported here:
"Labels of PST02 in Secure Mode are wrong in ozwcp"
https://github.com/OpenZWave/open-zwave/issues/1899
This is the first step in fixing that issue, the next step is supporting multipart secure messages
This PR was tested by using both a real PST02 and data simulated by injecting valid and invalid data.
The PST02 sends a multipart secure message, the first part now logs:
```
2019-09-04 09:51:13.429 Info, Node013, Multi-command frame received, encapsulates 4 command(s)
2019-09-04 09:51:13.431 Info, Node013, Received Battery report from node 13: level=100
2019-09-04 09:51:13.434 Detail, Node013, Refreshed Value: old value=100, new value=100, type=byte
2019-09-04 09:51:13.435 Detail, Node013, Changes to this value are not verified
2019-09-04 …
```
=> MultiCmd: implement sanity checks and improve logging

cpp/build/ozw_config.in
Change "test ==" to "test =" to improve portability.  (POSIX sh
specifies = for test, but bash accepts == also.)
=> ozw-config.in: Use = in sh test

config/idlock/idlock150.xml, config/manufacturer_specific.xml
This updates the config for the IDlock 150 module based on the spec of the latest 1.6 firmware from the manufacturer ([documentation](https://idlock.no/wp-content/uploads/2019/08/IDLock150_ZWave_UserManual_v3.02.pdf)).
I've also reordered the metadata items so they have the same order as the config template, and made some naming/text adjustments as per the Adding Devices wiki page.
There is a breaking change here for config index=2 regarding RFID mode, but the device reports the same type so I'm not sure how to be backwards compatible?
=> Update Idlock 150 config file for 1.6 firmware

cpp/build/testconfig.pl
Use number of keys instead of size(hash)
Without this PR and no errors:
```
perl cpp/build/testconfig.pl
Checking Config Files... Please Wait
Errors: (Please Correct before Submitting to OZW)
Saving Revision Database
```
After this PR
```
Checking Config Files... Please Wait
No errors detected (You can submit your changes to OZW)
Saving Revision Database
```
If I edit config/manufacturer_specific.xml after this PR:
```
Checking Config Files... Please Wait
config/manufacturer_specific.xml - md5 does not match Database - Database Revision:54 File Revision:54
Errors: 1. (Please Correct before Submitting to OZW)
config/manufacturer_specific.xml: Revision Number Was Not Bumped - Error Code 8
```
=> Fix testconfig.pl error printing

cpp/src/Driver.cpp
Before this PR, ProcessMsg only checks _data[5] (and type is request) to determine if the serial packet is a security CC and should be subject to nonce handling and encryption.
I would say that is only valid if the serial packet is of type "application command handler".
I am not sure if this would make a huge difference in practice...
=> Check if packet is actually device data before checking security

cpp/src/platform/unix/LogImpl.cpp
The dark blue that was assigned to "Detail" is hard to read on a black background.
Fixes a small, but to me quite annoying readability problem.
Feel free to ignore or suggest another color scheme ;)
=> Console log unix: change dark blue to light blue, add more colors.

.gitignore, cpp/test/Makefile, cpp/test/ValueID_test.cpp
Edit Makefile to clarify "make test" must be run in root of repository.
Add c++11 flag en link resolv library.
Re-enable equality test in cpp/test/ValueID_test.cpp.
=> Fix "make test"

cpp/src/Group.cpp, cpp/src/Group.h, cpp/src/Manager.cpp, cpp/src/Manager.h, cpp/src/command_classes/MultiChannelAssociation.cpp, cpp/src/command_classes/MultiChannelAssociation.h
Wherever posible, voriables, comments and log suggesting "instance" have been renamed to "endpoint". There is no functional change. It improves readability of the code.
Rationale:
When dealing with MultiInstance Devices, OpenZWave uses "Instance" to identify a subdevice. The public interface maps an Instance ID to an "End Point", which in turn gets used to build Z-Wave packets.
Config files and by extension ozwcache store this map per CC, for example:
<Instance index="1" endpoint="1" />
The Group aka Association commands, however, expect "End Points".
It would make sense to change "Instance" to "End Point" in *all* related code but this is not possible, there is one exception: InstanceAssociation is exposed by the API, in Manager::GetAssociations. Because of its exposure, m_instance …
=> MultiChannel code: change wording instance -> endpoint

cpp/src/command_classes/ClimateControlSchedule.cpp
I noticed throughout application that 95% of the time GetValue is retreived/used via a 'if statement like:
```
if (Internal::VC::ValueSchedule* value = static_cast<Internal::VC::ValueSchedule*>(driver->GetValue(_id)))
{
res = value->.....
```
This is not done on some locations, and could also aid checking against nullptr's
This patch also 'releases' the values
=> Making GetValue code more consistent, Releasing values

cpp/src/value_classes/Value.cpp, cpp/src/value_classes/Value.h
Resolves #1980 
Patch adds additional parameter to every Z-wave value in config xml: `refresh_after_set`. By default it is turned on (no changed behavior by default), but user can turn it off manually for devices that do not need constant verification.
Smart lighting in my Z-wave network consists solely of recent Aeotec and Fibaro devices that all send SwitchMultiLevel report on their own whenever you update them. By disabling redundant get commands, my network's responsiveness has increased significantly, especially when changing multiple lights at once or when changing color on bulbs.
=> Make set after get optional

cpp/src/command_classes/SensorBinary.cpp
I noticed bogus Binary Sensor numbers in the log, for example:
Node002, Received SensorBinary report: Sensor:199 State=On
Based on serial frame:
Received: 0x01, 0x0b, 0x00, 0x04, 0x00, 0x02, 0x03, 0x30, 0x03, 0xff, 0xc7, 0x00, 0xfa
Length of the CC is 0x03, payload is 0x30, 0x03, 0xff, so OZW mistakenly takes next byte as "Sensor Type"
The length test was off by one.
After this patch:
Node002, Received SensorBinary report: State=On
V2 reports still work:
Received: 0x01, 0x0a, 0x00, 0x04, 0x00, 0x02, 0x04, 0x30, 0x03, 0xff, 0x0c, 0x37
Node002, Received SensorBinary report: Sensor:12 State=On
This probably did not cause apparent issues because the bogus sensor type isn't likely to be in the "SensorMap"
=> Fix SensorBinary V1 decoding

cpp/src/Node.cpp
IMHO if the Multichannel CC is net before, but only after the "mark" then the device is not multi channel.
Adds log:
2019-12-05 10:34:57.454 Detail, Node004, Skipping RequestInstances() because MultiChannel CC is "after mark"
Fixes "Problems with ZME_WALLC-S after Update from 1.4 to 1.6 - states missing" #2020 by not doing 17 requests that all time out...
=> Don't request Instances is Multichannel is "after mark"

cpp/src/Driver.cpp
lldb complained:
Driver.cpp:2701:43: error:
result of comparison of constant -1 with expression of type
'uint8' (aka 'unsigned char') is always false
[-Werror,-Wtautological-constant-out-of-range-compare]
Add some info to debug logging
=> Fix comparison uint8 with -1, also test if controller node is 0.

cpp/src/platform/unix/SerialControllerImpl.cpp
I noticed... I could run many instances of MinOZW on the same port, on my Mac, or MinOZW and "picocom" on the same port...
This will make OZW retry as if it failed to open the port.
Prints this if it cannot get an exclusive lock:
ERROR: Cannot get exclusive lock for serial port /dev/cu.usbmodem14101. Error code 35
=> Make flock(m_hSerialController... actually do something

cpp/build/support.mk, dist/openzwave.spec
Potential fix for git version "dirty" flag.
Might help diagnose "revision on build server always 1.6.0".
When entering support.mk a second time, git describe returns "dirty" flag although I saw no immediate cause.
According to the docs, --git-dir should be used with --work-tree, or use the -C flag, introduced in git 1.8.5-ish.
Added debugging (Makefile warnings).
Tested on macOS Catalina and Debian 8 (Jessie), released 25–26 April 2015. Not tested on Debian 7 (Wheezy), released 4 May 2013 because Wheezy does not come with C++11 compiler by default.
Does not alter the way the version (and its parts) is determined, so still prints eg "Building OpenZWave Version 1.6-987-g555bf05e"
If git is missing, prints a warning: "open-zwave/cpp/build/support.mk:45: git executable not found, setting …
=> Updates to "OZW revision" (git describe) script on Unix

cpp/src/Driver.cpp
If a network consists of sleeping nodes (and they sleep) none of the notifications Type_AwakeNodesQueried Type_AllNodesQueriedSomeDead Type_AllNodesQueried is send because all messages are moved to the wake up queue.
Reported by Gilles Printemps, https://groups.google.com/d/msg/openzwave/THGYQ1jqKF4/cZPF5FEDBQAJ
It is a bit of a corner case, and I could not think of an easier way to handle this, I am open to suggestions.
=> Call CheckCompletedNodeQueries in MoveMessagesToWakeUpQueue

cpp/src/value_classes/ValueList.cpp
Before this commit, it is possible to have an infinite loop and log filling with:
"Warning, Item value  is wrong type or does not exist in xml configuration for node 9, class 0x70, instance 1, index 1"
This is because the code skipped "itemElement = itemElement->NextSiblingElement();"
IMHO only happens with corrupt or edited ozwcache file.
=> Fix a possible infinite loop with invalid list configuration data

cpp/src/Driver.cpp
I simulated a busy network and observed:
2019-12-25 08:48:05.800 Info, contrlr, Sending (Command) message (Callback ID=0x00, Expected Reply=0x15) - FUNC_ID_ZW_GET_VERSION: 0x01, 0x03, 0x00, 0x15, 0xe9
2019-12-25 08:48:05.800 Info, contrlr, Encrypted Flag is 0
2019-12-25 08:48:05.801 Detail, Unsolicited message received while waiting for ACK.
2019-12-25 08:48:05.802 Detail, Node012,   Received: 0x01, 0x0f, 0x00, 0x04, 0x00, 0x0c, 0x07, 0x60, 0x0d, 0x00, 0x01, 0x25, 0x03, 0xff, 0xdd, 0x00, 0x97
2019-12-25 08:48:05.802 Detail,
2019-12-25 08:48:05.803 Detail, contrlr, CAN received...triggering resend
2019-12-25 08:48:05.803 Detail,
2019-12-25 08:48:05.803 Info, contrlr, Sending (Command) message (Attempt 2, Callback ID=0x00, Expected Reply=0x15) - FUNC_ID_ZW_GET_VERSION: 0x01, 0x03, 0x00, …
=> Fix handling of controller CAN

config/aeotec/zw175.xml, cpp/build/testconfigversions.cfg
```
I own a few of these devices (with firmware 1.02) and found the
configuration applied did not match the description in Open-Zwave.
- Parameter 101 controls the periodic power reporting. The description
before this change was all wrong. The Aeotec manual updated November 2019
[1] appears to be wrong about bits 2 & 3 (values 4 and 8); they seem
reversed in practice.
- Parameter 111 controls the interval for the periodic power reporting. The
Aeotec manual updated November 2019 [1] mentions that the minimal
interval is 30 seconds, not 600. The factory default is 600, though.
[1]: https://aeotec.freshdesk.com/support/solutions/articles/6000219911-smart-switch-7-user-guide-
(version "Modified on: Wed, 13 Nov, 2019 at 10:45 PM")
```
=> Update configuration parameter descriptions for Aeotec ZW175

config/hank/hkzw-ms02-200.xml, config/hank/hkzw-ms02-300.xml, cpp/build/testconfigversions.cfg
According to the product manual, this parameter controls how much
additional delay will be used to control directly associated devices, and
it has nothing to do with a luminance level (this is not a luminance
sensor).
=> Update Hank HKZW-MS02 configuration parameter 18 description

config/qubino/ZMNHYDx.xml, cpp/build/testconfigversions.cfg
- Fix typo 'disbale' -> 'disable'
- Fix '2 and 6 combined' to '2 and 3 combined', as 6 would refer to itself.
(It is '2 and 3' as per Qubino user manual.)
- Improve sentence in parameter 52.
=> Update configuration descriptions for Qubino Smart Plug 16A (ZMNHYDx)

config/2gig/ct32.xml, cpp/build/testconfigversions.cfg
Fix the 1) setpoint detection and some 2) incorrect config parameters.
1. Disable the AltTypeInterpretation compat flag. When this flag is enabled (the default), OZW will process the thermostat setpoint supported report bitmask value as Interpretation B. This causes the Energy Save Heating (A bit 1.7) and Energy Save Heating (A bit 2.0) to be interpreted as Furnace (B bit 1.7) and Dry Air (B bit 2.0). The spec says all implementations must comply with Interpretation A, so I'm not quite sure why it isn't the default.
2. Some config params had incorrect or minimal help text, and incorrect default values. The Temperature Swing setting was missing several values.
=> CT32 thermostat config file updates

config/qubino/ZMNHHDx.xml, cpp/build/testconfigversions.cfg
Adjustments according to the [manual][1] on parameter 65:
* The type is "1 byte dec" corresponding with "byte" in OZW, but this was
"short", so the device ignored the setting.
* The maximum value is 127, not 255.
* The default value is 1, not 100.
* The description about the valid value range appears untrue (1-255) as
well as a 10-ms step per value.
Relevant Qubino support interaction in ticket [#4847][2] point 1.
[1]: https://qubino.com/wp-content/uploads/2019/09/Qubino_Mini-Dimmer-PLUS-extended-manual_eng_3.4_09092019.pdf
[2]: https://support.qubino.com/public/tickets/cc6122dca894548e0b935144554a874e3da214108f079fbe34cc51b429ae3891
=> Qubino ZMNHHDx Mini Dimmer: fix value type of config parameter 65

config/SensorMultiLevelCCTypes.xml
Matter is spelled with 2 t's:
https://www.merriam-webster.com/dictionary/matter
https://www.merriam-webster.com/dictionary/mater
=> Fix particulate matter spelling

cpp/src/command_classes/Configuration.cpp
Fix maybe-uninitialized warning:
```
#5 80.71 Building src/command_classes/Configuration.cpp
#5 82.11 /src/open-zwave/cpp/src/command_classes/Configuration.cpp: In member function 'uint32 OpenZWave::Internal::CC::Configuration::getField(const uint8*, OpenZWave::Internal::CC::Configuration::CC_Param_Size, uint8&)':
#5 82.11 /src/open-zwave/cpp/src/command_classes/Configuration.cpp:84:12: error: 'value' may be used uninitialized in this function [-Werror=maybe-uninitialized]
#5 82.11    84 |     return value;
#5 82.11       |            ^~~~~
#5 82.88 cc1plus: all warnings being treated as errors
#5 82.90 make[1]: *** [/src/open-zwave/cpp/build/support.mk:192: /src/open-zwave/.lib/Configuration.o] Error 1
#5 82.90 make[1]: Leaving directory '/src/open-zwave/cpp/build'
#5 82.90 make: *** …
```
=> Fix maybe-uninitialized warning

config/aeotec/zw164.xml, config/manufacturer_specific.xml, cpp/build/testconfigversions.cfg
Adds identifier information for the North American frequency region version of the Aeotec Siren 6 (ZW164-A) to the existing device configuration metadata.
This information was fetched from the [Z-Wave Alliance data for the Aeotec Siren 6 ZW164-A](https://products.z-wavealliance.org/products/3284).
=> Adds North American ID information for Aeotec ZW164-A

cpp/src/Driver.cpp, cpp/src/Driver.h
1 - Motivation for the rename logging of "Serial API Version" to "Firmware Version":
a) "Serial API Version" is confusing, the serial IP does indeed have a "version" but that is not this one.
b) The spec calls it an "application version"... And that is what end-users commonly know as "firmware version"
INS12350-17 Serial API Host Appl. Prg. Guide
7.3 Capabilities Command
FUNC_ID_SERIAL_API_GET_CAPABILITIES
ZW->HOST: RES | 0x07 | SERIAL_APPL_VERSION | SERIAL_APPL_REVISION | SERIALAPI_MANUFACTURER_ID1 | SERIALAPI_MANUFACTURER_ID2 | SERIALAPI_MANUFACTURER_PRODUCT_TYPE1 | SERIALAPI_MANUFACTURER_PRODUCT_TYPE2 | SERIALAPI_MANUFACTURER_PRODUCT_ID1 | SERIALAPI_MANUFACTURER_PRODUCT_ID2 | FUNCID_SUPPORTED_BITMASK[ ]
SERIAL_APPL_VERSION is the Serial API application Version number. …
=> Rename Serial Version to Firmware Version and add Communication and Chip Version

config/fibaro/fgsd002.xml
according the fibaro website the default for parameter 12 is 0 and not 255. This is now corrected
=> parameter 12 has wrong default in description

cpp/src/command_classes/Configuration.cpp
Fixed compile time warning on Ubuntu 19 arm64:
```
Building src/command_classes/Configuration.cpp
/home/ubuntu/github/open-zwave/cpp/src/command_classes/Configuration.cpp: In member function ‘virtual bool OpenZWave::Internal::CC::Configuration::HandleMsg(const uint8*, uint32, uint32)’:
/home/ubuntu/github/open-zwave/cpp/src/command_classes/Configuration.cpp:263:41: error: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Werror=format-truncation=]
263 |       snprintf(label, 16, "Parameter #%d", parameter);
|                                         ^
In file included from /usr/include/stdio.h:867,
from /usr/include/c++/9/cstdio:42,
from /usr/include/c++/9/ext/string_conversions.h:43,
from /usr/include/c++/9/bits/basic_string.h:6493,
from …
```
=> Fix snprintf truncated value

config/aeotec/zw162.xml
Add the parameter 0x60 (96), a boolean to specify if the action button stops the currently playing chime.
Also update the link to the Doorbell 6 technical docs.
Relevant part of the docs. It specifies the read/write option no. 96, with a default of "0", size of "1".
=> Add missing option for ZW162 (Aeotec Doorbell 6)

config/manufacturer_specific.xml
There is a new revision of Fibaro FGT-001 Heat Controller with new id `0001`.
=> Add additional identifier for the Fibaro FGT-001 Heat Controller

config/manufacturer_specific.xml, cpp/build/testconfigversions.cfg
Add an entry in the MFS for the Silicon Labs (was Sigma) UZB3 Z-Wave USB stick.
`make xmltest` updated file testconfigversions.cfg for some device files I did not touch. I presume they were not updated from another PR.
=> Add MFS entry for Silicon Labs USB3 Z-Wave USB stick

config/manufacturer_specific.xml, config/mcohome/mh9co2.xml
Add support for MCO Home MH9 multisensor with different type and id than currently in de DB and improve config file to include all config options.
=> Add support for different MCO Home MH9 and extend config options

config/zooz/zen27.xml, config/zooz/zse29.xml
- Zen27 update to reflect the min value of 0 for parameter 9
- ZSE29 config parameters added and are valid for firmware 2.0
=> Updates for Zooz Zen27 and ZSE29

config/kwikset/914c.xml, cpp/build/testconfigversions.cfg
Changed the index value of the alarm message that should trigger a refresh.
=> fixed kwikset 914c alarm message index for refresh

config/assa_abloy/TouchDeadbolt.xml
See https://github.com/OpenZWave/qt-openzwave/issues/105, and https://github.com/OpenZWave/open-zwave/pull/2256
Proper refresh lock status when lock is manually operated.
=> Fix YRD446 alarm message index for refresh

config/homeseer/hs-wd100plus.xml, cpp/build/testconfigversions.cfg
OZW is not reporting the final dimming value of the HS-WD100+.  This change adds the `VerifyChanged` compatibility setting to resolve the issue.  Tested against HS-WD100+ firmware 5.19.
=> Add VerifyChange to Homeseer HS-WD100+ to resolve out-of-sync state

config/manufacturer_specific.xml
Use the ZEN23v3 config by default for advanced config settings. Vendor used same node identity codes as old hardware that can't be updated; changing to new config since this is what is still being sold today. As far as I can see having new config options on old hardware doesn't cause any problems, they are just ignored / don't do anything.
=> Update for revised Zooz ZEN23 config

config/assa_abloy/PushButtonDeadbolt.xml
Manual lock and unlock operations for the Assa Abloy YRD216 Touch Button Deadbolt do not automatically refresh the values for the `COMMAND_CLASS_DOOR_LOCK` status values:
CommandClass 98 Instance 1 Index 0 "Locked" Boolean
and
CommandClass 98 Instance 1 Index 1 "Locked (Advanced)" list
This commit adds a value refresh trigger on the `COMMAND_CLASS_NOTIFICATION` Instance 1 Index 6 "Access Control" value which changes on manual, keypad, and wireless lock/unlock operations to update the overall lock status.
This change is similar in nature to #2260, #2256 and https://github.com/OpenZWave/qt-openzwave/issues/105.
=> Fix YRD216 alarm message index for value refresh

config/ge/12720.xml, config/manufacturer_specific.xml
This is the older non-plus revision of the ZW4201 GE/Jasco Outdoor Plugin Smart Switch.  The product images are exactly the same, the casing of the product was the same for both revisions.
The manual is not available on Zwave alliance DB, I added another one I found though.
=> Add support For Ge 12720

config/schlage/BE468.xml
Index should be 6 instead of 0. This was previously fixed for the BE469 locks but not the BE468.
=> Fix TriggerRefreshValue for Schlage BE468 locks

config/inovelli/lzw30-sn.xml, config/inovelli/lzw30.xml, config/inovelli/lzw31-sn.xml, config/inovelli/lzw31.xml
The newest firmware for the LZW31-SN adds 2 new parameters. Details can be found [here](https://support.inovelli.com/portal/en/kb/articles/firmware-v1-47-beta-lzw31-sn-dimmer-red-series-gen-2).
Config parameters name and description pulled from the Hubitat "driver"
=> Update LZW31-SN Parameters for 1.47

config/kwikset/910.xml, config/kwikset/smartcode.xml, config/manufacturer_specific.xml
Replacement PR for #2304 
Unit testing shows 512/513 are the `alarm_type` and `alarm_level` reports that this lock uses instead of proper Notifications.
=> [Config Update] Kwikset Locks: New 910/914 XML (non-zwave+ versions)

config/honeywell/th8320zw1000.xml
I own this thermostat and trying to send the value with only 1 byte results in it dropping to the lowest value (10 degrees Celsius) if you send a decimal value (such as 23.5).
Setting the precision to 2 solves it. See #1239 for more information.
=> Honeywell TH8320ZW1000 thermostat requires 2 bytes for precision

config/ge/14294-dimmer.xml, cpp/build/testconfigversions.cfg
Remove duplicate metadata that was from a different product.
Add some undocumented configuration parameters. These are documented in newer revisions and work fine in this version. They should work with firmware version >= 5.26.
Interesting [discussion ](https://community.getvera.com/t/ge-14294-operation/197000/3) at the Vera community about these  undocumented parameters.
Thanks to KeithL in the HA community for [bringing this up](https://community.home-assistant.io/t/ozw-beta-can-t-set-parameter-not-in-device-xml/226588)!
=> Update GE 14294 device XML

config/honeywell/th6320zw2003.xml
I own this thermostat and had to make this change in my config file to stop the thermostat from setting the temperature to 10 degrees Celsius when setting a decimal temperature like 21.5 degrees.
Very similar to this recent PR https://github.com/OpenZWave/open-zwave/pull/2362 that also applies to this model. See also https://github.com/OpenZWave/open-zwave/issues/1239.
=> Update Honeywell T6 Pro th6320zw2003 Precision to 2

config/linear/LB60Z-1.xml
Add missing configuration params for setting up how fast the bulb will dim/bright.
These settings are critical to make the bulb work with Home Assistant successfully. 
The default settings make the bulb change gradually, which causes HA to be out of sync with the bulb's state. Setting Level = 99 and Speed = 1 fixes that by making the bulb react immediately.
=> Update LB60Z-1 configuration params

cpp/src/command_classes/Basic.cpp, cpp/src/command_classes/SwitchBinary.cpp
Leviton DZ15S and maybe other switches that support Version 2, don't send a V2 report, but still send what appears to be a V1 report without the Target vale.  This checks the payload length as well as version. (the pattern currently used in Basic CC).
=> SwitchBinary CC to include payload length before assuming V2 message content

config/aeotec/zw141.xml
* Trip times were decimal while they should be short
* Added actual list items to the repositioning and confirmation triggers
=> Fix config values for Aeotec Nano Shutter

config/manufacturer_specific.xml, config/remotec/zts-500.xml
The AU version has a type of 0202 instead 0200 but is otherwise identical. Added the necessary lines for it to be recognized.
I cannot find a differing product code or manual for the AU version.
=> Include AU version of ZTS-500

config/schlage/BE469ZP.xml
Based on this https://github.com/OpenZWave/Zwave2Mqtt/issues/742
and the BE469 lock that was updated. 
Solving error 
```
OpenZWave Info, Node101, Got a AlarmCmd_Report Message....
OpenZWave Info, Node101, Received Notification report (>v1): Type: Access Control (6) Event: Keypad Unlock Operation (6) Status: true, Param Length: 1
OpenZWave Warning, Node101, Couldn't Find ValueID_Index_Alarm::Type_ParamUserCodeid
OpenZWave Warning, Node101, Couldn't Find a ValueList for Notification Type 6 (1)
```
=> BE469ZP User index="6" update

cpp/src/Node.cpp
We need to update static request flags only after receiving all secure command classes, cause sometime on node refres command class version is received at the end.
Fixes: #2403
=> Update static request flags after receiving all secure command classes

config/cooper/RF9540-N.xml
Opposite to the spec, group 255 allows 0 associations is reported
from the device. Issue discussed here:
https://community.home-assistant.io/t/stuck-on-associations/136980/6
=> Update Cooper RF9540-N device

config/manufacturer_specific.xml
Add support for Fibaro Door Window Sensor 2 Australia
https://products.z-wavealliance.org/products/2294?selectedFrequencyId=4
=> Add support for Fibaro Door Window Sensor 2 Australia

config/ge/26932-motion-dimmer.xml
This flag solves Multilevel V2 transition issues on GE 26932.
=> GE 26932: add VerifyChanged flag to solve dimmer issues

config/ge/26931-motion-switch.xml, config/ge/26932-motion-dimmer.xml
Add ForceInstance=false flag to fix issue when adding association 1.0.
Without this flag, adding association '1.0' will become '1.1' silently.
=> Jasco/GE 26931,26932: Add ForceInstance=false flag

config/vision/zp3102.xml
This config is mentioned in the manual text but is undocumented in the spec.
Tested working. Note: it only accepts value 1 (+-1 degree) and 2 (+- 2 degree).
=> Vision ZP3102: Add config 5 to set temperature report change.

config/honeywell/39358-ZW4002.xml
The Honeywell 39358 is manufactured by Jasco and is similar to the GE Fan Control also manufactured by Jasco [config/ge/12724-dimmer.xml](../blob/master/config/ge/12724-dimmer.xml).
The control set for the LEDs is the same between the two devices and I have tested this out on 2 that I own.
=> [Config] Add LED config for Honeywell 39358 Fan Control

config/manufacturer_specific.xml, config/thermofloor/heatit021.xml
TF016 is the earlier version of TF021. After firmware upgrade of the device, it has a different ID and is not recognized by openzwave. This PR fixes this issue
=> Assigned TF016 to same config as TF021

config/aeotec/zw111.xml, config/aeotec/zw116.xml, config/aeotec/zw132.xml
As discussed on https://github.com/OpenZWave/qt-openzwave/issues/60, only way to use get Basic events going forward is to add couple of flags to the devices that support this.
These three devices all support basic command independently from controlling the load (e.g. pressing the physical switch can trigger basic set independently of controlling the actual load connected to those switches) and thus I think it is useful for OZW to also report basic status independently from actual load status.
=> Add basic command class to Aeotec switches and dimmers

config/manufacturer_specific.xml
Homeseer started shipping the HSM200 with manufacturer id=000c instead of the previous value 001e.  Copied the product line into the new section as the device appears otherwise unchanged.
=> Add Homeseer HSM200 to Manufacturer id=000c

config/manufacturer_specific.xml
Commit 607dd7a931f20a747812d3009a9a51cb7db55f6a accidentally removed the newly added Fibaro Flood sensor with `id=2003` added in PR #2050. 
This commit re-adds the Fibaro Flood sensor variant to the `manufacturer_specific.xml`.
=> Re-add Fibaro Flood Sensor with id 2003

config/ge/12724-dimmer.xml, config/ge/14291-switch.xml, config/ge/14292-toggle-switch.xml, config/ge/14294-dimmer.xml, config/ge/46201-switch.xml, config/honeywell/39348-zw4008.xml
This will cause Basic Set, usually treated as a Node Event, to be converted to a Value type.
Thread talking about about the fix:
https://github.com/OpenZWave/qt-openzwave/issues/60#issuecomment-664781107
=> Adding COMMAND_CLASS_BASIC blocks to GE/Honeywell/Jasco switches that support double tap and default double tap association auto=true

cpp/src/Manager.cpp
Change the exception to a unique message indicating an error in the
SetValue() function, rather than GetValueFloatPrecision().
My logs contain many instances of the previous message from a Button:
```
Warning, Exception: Manager.cpp:2499 - 102 - ValueID passed to GetValueFloatPrecision is not a Decimal Value
```
I'm not sure if the error is occurring in GetValueFloatPrecision() or
SetValue(), either way this line needs to be corrected.
=> fix: Correct SetValue exception message on Schedule and Button

config/ring/contact-sensor-v2.xml
Config 6 is misdocumented in z-wave alliance. The true values are
read(tested) from the device.
=> Ring Alarm Contact Sensor: minor fix

config/aeotec/zw095.xml
Please see the discussion here https://github.com/OpenZWave/open-zwave/issues/2214 for more about this issue.
I have made this change locally and then added the device to my network and tested that I am seeing updates on the device now.
=> Update zw095.xml to configure ordinary lifeline association instead of multi channel lifeline association

config/inovelli/lzw45.xml
The range for this parameter is too narrow.  Currently the max value accepted by the device is 197375.
=> Update Max Value of Inovelli LZW45 Parameter 30

config/zooz/zen16.xml
Add parameters 21 through 24 for device firmware 1.03 (https://www.support.getzooz.com/kb/article/356-zen16-multirelay-change-log/)
------------------
Firmware: 1.03
Added the ability to change relays to NC (normally closed) and customize on/off reports based on the switch / relay position
Added DC motor control mode which prevents R1 and R2 to be turned on at the same time
=> Additional parameters for zen16

config/dome/0104.xml, config/manufacturer_specific.xml
There's a new hardware variant of the Dome Mouser z-wave pest trap out there. The device is functionally the same as the old 0086 id device but is now id 0104.
=> Support new Dome Mouser id version 0104

config/manufacturer_specific.xml
I received a batch of these Shenzhen Neo water sensors via an Alibaba seller that report as a new type/id not known OZW. 
In case it's relevant, the only other difference I've noticed from a prior order of these sensors is that this batch does not send `SensorBinary` reports when triggered.
=> feat: add new type/id for shenzhen neo water sensor

config/cooper/RF9501.xml
RF9501 has an invalid group in the config that causes the ZWave controller to go into an endless loop. I've removed the invalid group.
=> Removed Invalid RF9501 Group

config/manufacturer_specific.xml
The European version of the TKB home TZ67 dimmer plug has a different ID and type compared to the included version. This version is called TZ67G
When copying the line for the TZ67 but changing the id and type accordingly, everything works perfectly. All functionality of the dimmer plug is there.
=> Added the European version of TZ67 called TZ67G

config/manufacturer_specific.xml
This was required to correctly map our newly purchased FGS-214 switch with OpenZWave.  
Thanks!
Monica
=> Added entry in manufacturers.xml for Fibaro Smart Module FGS-214 in EU

config/manufacturer_specific.xml, config/zooz/zen34.xml
Manufacturer sent information that a mass production of ZEN34 devices now have a new type code. No other changes.
=> Add entries for Zooz ZEN34 with different type code

config/zooz/zen23v3.xml
Zooz documentation indicates that Parameter 12 is the one responsible for controlling the 3-way switch type: https://www.support.getzooz.com/kb/article/317-zen23-on-off-toggle-switch-ver-4-01-advanced-settings/
Parameter 19 is for the Zen24, which is where I think the error came from.
=> Fix zen23v3.xml parameter 19 to 12

config/manufacturer_specific.xml
The new Zooz stick with 700 series chip is reporting with manufacturer 0000, type 0004 and id 0004. That manufacturer ID is in the list already for Sigma Designs but they don't have anything with id/type 0004 so I created a new Zooz entry with that manufacturer ID. I don't know what is the preferred way to handle such a thing. Maybe they'll get the manufacturer ID corrected on future production runs.
2021-02-09 09:57:36.850 Info, contrlr,     Manufacturer ID:      0x0000
2021-02-09 09:57:36.851 Info, contrlr,     Product Type:         0x0004
2021-02-09 09:57:36.851 Info, contrlr,     Product ID:           0x0004
=> Add Zooz ZST10 700 series USB controller

cpp/src/Driver.cpp
The `ozwcache_*.xml` file does not preserve white space. Config XML might contain useable formatting, so don't condense white space into a single space.
E.g., a configuration XML might contain:
```xml
<Help>This parameter allows to enable different additional functions of the device.
1) Enable open window detector (normal)
2) Enable open window detector (rapid)
4) Increase receiver sensitivity (shortens battery life)
8) Enable LED indications when controlling remotely</Help>
```
Currently this is stored in the OZW XML cache as:
```xml
<Help>This parameter allows to enable different additional functions of the device. 1) Enable open window detector (normal) 2) Enable open window detector (rapid) 4) Increase receiver sensitivity (shortens battery life) 8) Enable LED indications when …
```
=> Preserve whitespace in OZW XML cache

config/manufacturer_specific.xml, cpp/build/testconfigversions.cfg
I have two versions of MH9 CO2 at my place.
One version with id=3102 and type=0901.
Second one with id=5102 and type=0901.
=> Another id for MH9 CO2

config/aeotec/zw100.xml
Firmware 1.10 (10/24/2017) changed the size of configuration parameters 0x29, 0x31 and 0x32 from 3 to 4 bytes. As you can update the firmware of this device over the air, it makes sense to update the config xml to reflect these changes.
=> Fix errors in 1.10 firmware

config/manufacturer_specific.xml
Simon S100 dimmer 10002020-13X must have a new line with id="0000" along with "023a", because some dimmers have this ID assigned (similar case to Simon S100 Socket iO 10002034-13X)
=> Added new product ID 0000 for Simon S100 10002020 dimmer.

cpp/src/Msg.cpp, cpp/src/Msg.h, cpp/src/Node.cpp, cpp/src/Node.h, cpp/src/command_classes/CommandClass.h, cpp/src/command_classes/CommandClasses.cpp, cpp/src/command_classes/Supervision.cpp, cpp/src/command_classes/Supervision.h, cpp/src/command_classes/ThermostatSetpoint.cpp, cpp/src/command_classes/ThermostatSetpoint.h, cpp/src/value_classes/Value.cpp, cpp/src/value_classes/ValueDecimal.cpp, cpp/src/value_classes/ValueDecimal.h
[ I messed up #2525, so I created a new PR ]
Some devices like the Fibaro FGT001 Heat Controller won't accept a `ThermostatSetpointCmd_Get` right immediate after a `ThermostatSetpointCmd_Set`. The device returns instead:
0x22 = COMMAND_CLASS_APPLICATION_STATUS (See 4.2.2 Application Busy Command in SDS13782 Z-Wave Management Command Class Specification.pdf)
0x01 = APPLICATION_BUSY
0x01 = "Try again in Wait Time seconds"
0x02 = two seconds...
One solution would be to retry the `ThermostatSetpointCmd_Get` after 2 seconds. A more efficient approach is to encapsulate the `ThermostatSetpointCmd_Set` with a supervision CC. This was proposed in issue #1971 and is implemented in this PR. It works like this:
```
2021-02-13 16:46:12.338 Info, Node019, Value::Set - COMMAND_CLASS_THERMOSTAT_SETPOINT …
```
=> Use supervision to set thermostat setpoint

cpp/src/command_classes/ThermostatMode.cpp, cpp/src/command_classes/ThermostatMode.h, cpp/src/value_classes/ValueList.cpp, cpp/src/value_classes/ValueList.h
Following up on pull request #2584.
Made additions to support the supervision CC for the thermostat mode CC.
=> Making use of the Supervision CC to set the thermostat mode.

cpp/src/command_classes/SwitchMultilevel.cpp, cpp/src/command_classes/SwitchMultilevel.h, cpp/src/value_classes/ValueByte.cpp, cpp/src/value_classes/ValueByte.h
Following up on pull request #2584.
Made additions to support the supervision CC for the switch multilevel CC.
This one is especially useful for dimmers and window blinds (if the node supports it). The supervision CC is more reliable than the standard set/get method, which is often faster than the transition and things get messed up.
=> Supervision CC support for SwitchMultiLevel
