OpenZWave/open-zwave

cpp/src/command_classes/CRC16Encap.cpp
cpp/src/command_classes/CRC16Encap.h

Implemented CRC16Encap support based on the CRC-CCITT algorithm.

implemented CRC16Encap support

---

config/widom/UBS104.xml

As required here the pull request.
King regards

config/widom/UBS104.xml: shortened some labels

---

.gitignore
config/manufacturer_specific.xml

Added some Vitrum Wireless IDs&Types that weren't already included and edited the gitignore file to ignore compiled libs and other files.

Added some Vitrum Wireless switches and edited gitignore file

---

config/swiid/swiidinter.xml

Add swiidIter configuration file

---

config/manufacturer_specific.xml
config/philio/pst02.xml

This device http://www.philio-tech.com/products/PST02-A.pdf
I hope this time everithing is as you expected, I don't wan't give you a overhead for every pull request I perform.

add Philio PST02-A 4 in 1 Multi-Sensor

---

cpp/build/windows/vs2010/OpenZWave.vcxproj

Fixed windows build event (winversion.cpp generation)

---

cpp/src/Driver.cpp
cpp/src/Driver.h
cpp/src/Group.cpp
cpp/src/Group.h
cpp/src/Manager.cpp
cpp/src/Manager.h
cpp/src/Node.cpp
cpp/src/Node.h
cpp/src/command_classes/MultiInstanceAssociation.cpp
cpp/src/command_classes/MultiInstanceAssociation.h

continuation of #560, rebased to New-CC branch

[RFC] MultiInstanceAssociation support

---

config/device_configuration.xsd
cpp/src/Group.cpp
cpp/src/Group.h
cpp/src/command_classes/MultiInstanceAssociation.cpp
cpp/src/command_classes/MultiInstanceAssociation.h

I hope this fixes the windows build errors, since I have no windows / visual studio I can not test my self.
I also introduced a multiInstance config option at group level since apparently not all groups are  multiInstance capable.

MultiInstanceAssociation windows fix?

---

config/manufacturer_specific.xml
config/zwave.me/ZME_WALLC-S.xml

Add configuration for Z-Wave.Me  ZME_WALLC-S Secure Wall Controller

add Z-Wave.Me: ZME_WALLC-S Secure Wall Controller

---

config/aeon_labs/ses2.xml
config/manufacturer_specific.xml

remove parameter 1
adapte parameter 2, with more details help and default value
add parameter 3 Current Overload Protection
add parameter 20 Output Load Status
adjust some labels and default values
add parameter 200 Partner ID
add parameter 252 Configuration Locked
rename group 2 and remove auto attribute

update smart switch gen5

---

config/fibaro/fgs212.xml
config/fibaro/fgs222.xml
config/manufacturer_specific.xml

To set theAuto off fgs212 (param 4) and fgs222 (param 4 and 5) we have to set a short value not a byte.
this is apply also for FGS211 in version 2.1 - 2.8 and FGS221 in version 2.1 - 2.3 but I dont have the specifc product type and id.

add specific configuration files for fgs212 and fgs222

---

ChangeLog
config/everspring/ad147.xml
config/manufacturer_specific.xml
distfiles.mk

(first PR ever, sorry in advance if I messed up something :) )
Adding support for two devices I own, Aeotec DSC24 and Everspring AD147.
AD147 gets a special config file to switch between dimming and on/off mode.
Please review and comment

Add Aeotec DSC24 and Everspring AD147

---

cpp/src/command_classes/Alarm.cpp
cpp/src/command_classes/Alarm.h

* Updated the list of alarm names
* added logging when receiving an alarm message with version > 1 info
* update get request for version >1
* AlarmIndex_SourceNodeId is reported in _data[3], _date[4] seems to be the status

Update Alarm CommandClass

---

config/everspring/st812.xml
config/manufacturer_specific.xml

Add xml file for Everspring st812-Flood Detector

Add Everspring st812-Flood Detector

---

config/manufacturer_specific.xml
config/qubino/ZMNHBD2.xml

It's similar, to the ZMNHBA2, but id and internal parameters are different

Added Qubino ZMNHBD2 Flush 2 Relays module

---

config/fortrezz/mimolite.xml
config/manufacturer_specific.xml
cpp/build/Makefile

Parameters from technical appendix published by fortrezz: http://www.lorenzhd.com/thesmartesthouse/downloads/fortrezz-mimolite-technical-appendix.pdf
Ran xmltest to verify properly-formed XML this time - sorry about the sloppy pull request last time!

Configs for fortrezz MIMOlite

---

config/popp/123580.xml
cpp/src/Manager.h
dotnet/src/ZWManager.h

Just some stuff that caught my eye when looking around.

Minor fixes

---

config/manufacturer_specific.xml
config/popp/POPE009105.xml

Added configuration file for the POPP Wall Plug Switch Schuko (IP44) with id POPE009105.
Tested it live via Domoticz with my device and everything seems to work just fine.

Added OZW config file for POPP Wall Plug Switch Schuko (IP44).

---

config/manufacturer_specific.xml

Hello,
The US version of the Fibaro fgms has a different id than the two existing. Added it and tested in Domoticz.
Thank you!

Added US version of Fibaro FGMS-001

---

config/manufacturer_specific.xml

Sorry for the noise late file, but looks like nothing that effects anything, if you want me to clean and redo let me know.
Primarily added 2 product numbers for a few sensors i have that were not getting set because they were slightly different.

Added product numbers for FIBARO motion sensor, and door sensors.

---

config/enerwave/zw15s.xml
config/enerwave/zw20r.xml
config/enerwave/zw500d.xml
config/manufacturer_specific.xml

The ZW15S doesn't advertise its configuration parameters, so it requires manufacturer-specific data.

 ZW15S config params

---

config/manufacturer_specific.xml
config/qubino/ZMNHAA2.xml
config/qubino/ZMNHAD1.xml
config/qubino/ZMNHBA2.xml
config/qubino/ZMNHBD1.xml
config/qubino/ZMNHCA2.xml
config/qubino/ZMNHCD1.xml
config/qubino/ZMNHDA2.xml
config/qubino/ZMNHIA2.xml
config/qubino/ZMNHID1.xml
config/qubino/ZMNHJD1.xml
config/qubino/ZMNHLD1.xml
config/qubino/ZMNHND1.xml
config/qubino/ZMNHOD1.xml
config/qubino/ZMNHSD1.xml
config/qubino/ZMNHUD1.xml
distfiles.mk

Merge in Qubino Supplied Config Files...

Qubino Submitted Config Files

---

config/manufacturer_specific.xml

Door/Window Sensor also has a Dry Contact switch, very affordable. 
not sure why this ended up as 3 commits, i must of messed up my repo.. sorry.

Ecolink Door/Window Sensor

---

config/enerwave/zwn-bpc.xml
config/manufacturer_specific.xml
distfiles.mk

Add a configuration for the Enerwave ZWN-BPC Ceiling Mounted PIR Motion Sensor.

Add Enerwave ZWN-BPC configuration

---

config/manufacturer_specific.xml
config/remotec/zts-110.xml

Values (and as much as possible descriptions) pulled from the manual from the manufacturer: https://www.remotec.com.hk/wp-content/uploads/2015/12/8031_V3.12_F820-8031-0004_40p_20140702.pdf

Configs for Remotec ZTS-110 thermostat.

---

config/manufacturer_specific.xml
config/philio/pse02.xml

My KFOB is only recognized when the KFOB line is added to the manufacturer Popp

Added Popp KFOB to Popp besides Z-Wave.Me

---

ChangeLog
config/2gig/ct50e.xml
config/manufacturer_specific.xml

Using same code as ct30.xml and has worked well for CT50e so far in testing.

Add 2gig CT50e thermostat with USNAP module RTZW-01

---

cpp/examples/MinOZW/Main.cpp

I've found the basic example somewhat unclear when starting to experiment with the library.
The suggested changes hopefully make it more clear on how to access the nodes available in the network.

Print the names for nodes and values that have beed detected in the network.

---

config/manufacturer_specific.xml

Add line for the GR-105N device. see http://www.pepper1.net/zwavedb/device/790

Update manufacturer_specific.xml for add GR-105N

---

config/enerwave/zw20rm.xml
config/manufacturer_specific.xml
distfiles.mk

Add configuration parameters for Enerwave ZW20RM 20A Smart Meter Duplex Receptacle

Device Support: Enerwave ZW20RM configuration params

---

config/domitech/zb22uk.xml
config/manufacturer_specific.xml

fix https://github.com/OpenZWave/open-zwave/issues/872

Device Support: Domitech Smart LED Light Bulb ZB22UK

---

config/danfoss/rs.xml
config/manufacturer_specific.xml

Hi,
Please add the following Configurations.
Regards, Christian

Add Danfoss RoomSensor and Duwi Static Controller

---

cpp/src/command_classes/DoorLockLogging.cpp

Botton->Button
Now I have this song in my head: https://www.youtube.com/watch?v=K4dx42YzQCE

fixed Botton typo

---

cpp/build/Makefile
cpp/build/support.mk

Signed-off-by: Bin Li <bin.li@windriver.com>
Makefile change to support building openzwave in bitbake environment ( Yocto Project )
https://github.com/OpenZWave/open-zwave/issues/848

fix for issue 848

---

config/aeotec/zw100.xml

Updates to the Aeotec Multisensor 6 configuration class text to correct and clarify - updated changes from https://github.com/OpenZWave/open-zwave/pull/806.

Multisensor 6 Help Text Update

---

config/manufacturer_specific.xml

Added GE 12727 In-Wall Smart Switch (Toggle) and tested

Added GE 12727 In-Wall Smart Switch

---

config/assa_abloy/KeyfreeConnected.xml
config/manufacturer_specific.xml

I have included a separate KeyfreeConnected.xml in this commit rather than just referencing RealLivingCapTouch.xml as I will be making further additions to KeyfreeConnected.xml.

Add device Assa Abloy Yale Keyfree Connected Smart Lock

---

ChangeLog
config/linear/LB60Z-1.xml
config/manufacturer_specific.xml

Adding support for the Linear (GoControl) dimming light bulb. 
Product information can be found at: http://products.z-wavealliance.org/products/1291

Add LB60Z-1 Dimmable LED Light Bulb

---

config/manufacturer_specific.xml
config/shenzen_neo/nas-wr01z.xml

Initial xmls for Neo Coolcam Power Plug

Neo Coolcam Power Plug

---

config/manufacturer_specific.xml
config/shenzen_neo/nas-ds01z.xml

initial commit, but pls review Associations, I'm not sure about them.
Pepper1 link: http://www.pepper1.net/zwavedb/device/952

Neo CoolCam Door/Window Detector

---

config/ge/receptacle.xml
config/manufacturer_specific.xml

Includes a new file to control the LED settings.

Added support for GE 12721 Lighting Control Duplex Receptacle

---

config/manufacturer_specific.xml

Futher info: http://domoticz.com/forum/viewtopic.php?f=24&t=12792&p=94597#p94581
User seems to have one with the added id.

Added another variant for Neo Coolcam PIR

---

config/devolo/mt2646.xml
config/manufacturer_specific.xml
distfiles.mk

Added Devolo Metering Plug .
Also added Permundo PSC132ZW Smart Mini Plug and PSC234ZW Smart Plug to manufacturer_specific.xml
I have some more devolo devices i'm going to add, would you prefere to have one PR for each device or one for all?

Devolo Metering Plug and Permundo Plugs

---

config/manufacturer_specific.xml
config/telldus/tzdw100.xml

modified:   config/manufacturer_specific.xml
new file:   config/telldus/tzdw100.xml

Unknown: id=0176 Unknown: type=0005, id=0001

---

config/fibaro/fgk10x.xml
config/manufacturer_specific.xml

The Fibaro FGK10x has significantly other configuration parameters and association group.
Add new config file for it.

Add/Correct Fibaro Door/Window Sensor FGK10x

---

config/devolo/mt2647.xml
config/manufacturer_specific.xml

Adding some devolo devices
Metering Plug MT 2646
Flood Detector MT 2756
Motion Detector MT 2647
Scene Switch MT 2652
Remote MT 2653

Devolo devices

---

config/idlock/idlock101.xml
config/manufacturer_specific.xml

Hi,
Please find attached a pull request for adding support for ID Lock 101.
[ID Lock 101 manual](http://idlock.no/media/wysiwyg/Bruksanvisning/IDL%20Operational%20Manual%20EN.pdf)

Suggestion for adding support for ID Lock 101

---

config/manufacturer_specific.xml
config/zooz/zse08.xml

My first ever pull request, so hope I got this right.
Adding new sensor, Zooz ZSE08 Contact Sensor.
http://www.thesmartesthouse.com/products/zooz-z-wave-plus-door-window-contact-sensor-zse08

Added Zooz ZSE08 Contact Sensor

---

config/manufacturer_specific.xml
config/zooz/zse09.xml

Added new device, zooz zse09

---

ChangeLog
config/ge/hinge-pin.xml
config/manufacturer_specific.xml

Tested hinge pin and new configuration..

Added GE 32563 Hinge Pin Smart Door Sensor config

---

config/cooper/RF9501.xml
config/cooper/RF9517.xml
config/cooper/RF9542-Z.xml
config/manufacturer_specific.xml

* RF9501 switch
* RF9517 accessory switch
* RF9542 accessory dimmer

Add definitions for 3 Cooper Aspire RF devices:

---

config/manufacturer_specific.xml

Added new device to manufacturer_specific.xml.  No configurations current available for device.

Added Zooz ZEN20 Power Strp

---

config/manufacturer_specific.xml

Included support for FGK101 type="0701" id="3001"

Included support for FGK101 type="0701" id="3001"

---

cpp/src/Driver.cpp

The ZME Wall Controller Wall C-S sends the SecurityCmd_MessageEncapNonceGet (0xC1). When this can not be decrypted (for example the `MAC Authentication of Packet Failed. Dropping` Error occured), the expected nonce-report does not get sent to the device. 
So, this now also sends the nonce-report on decryption fail.
Also fixes a bug that prevent the SecurityCmd_MessageEncapNonceGet to get recognized after the decryption.
It checked for _data[6], but _data[6] was already overwitten by the decrypted package.
This caused the Wall Controller to run into its timeout and wait for 20 seconds until another frame was sent.

Fix for Security handling

---

config/fibaro/fgwpe.xml

Signed-off-by: Christophe Vu-Brugier <cvubrugier@fastmail.fm>

Fix typo in fgwpe.xml: colorus -> colours

---

config/fibaro/fgmszw5.xml

Typo in fgmszw5.xml

---

config/fibaro/fgrm222.xml

Just fixed some small typo's and indentation.

Typo's & indentation

---

config/manufacturer_specific.xml

added new product and standardized naming conventions for tamper resistant (TR) for enerwave

add zw20rmplus

---

cpp/src/Driver.cpp
cpp/src/Notification.cpp
cpp/src/Notification.h

This is usefull in the ControllerCommand notification to the command that triggered the Notification.
see #1108
also added the ControllerCommand to the Notification::GetAsString()
Continued from #1117, bases on Dev branch

Discover controller command dev

---

config/manufacturer_specific.xml

Added another product type/id for Yale deadbolt YRD240

Added YRD240 (0002-0209)

---

config/manufacturer_specific.xml

add additional identifiers for yale locks

add additional identifiers for yale locks

---

config/manufacturer_specific.xml
config/philio/pan07.xml

Add Philio PAN07 device.
This is a unique device which seems not to be fully approved by Zwave alliance, but there are developer sample around on the market.

Add Philio PAN07 device

---

config/manufacturer_specific.xml

Add new ZRC-90 with a type of 0002

Add ZRC-90 Support Type 0002

---

ChangeLog
cpp/src/command_classes/MultiInstanceAssociation.cpp

Apply ForceInstances to associations to the controller only. 
Fixes issues #1142 and #1143

ForceInstances now limited to association with the controller node.

---

config/BeNext/TagReader500.xml
config/manufacturer_specific.xml

BeNext TagReader500 config files for Dev branch

BeNext TagReader500 config files

---

config/hank/hkzw-so01-smartplug.xml
config/manufacturer_specific.xml

this is for hank hkzw-so01 smart plug. tested with control panel and hass.
I did run "make dist-update" but looks like some other files are also added, I dot want add someone else's file. 
merger: Please  run "make dist-update" 
Thanks

Add hank hkzw-so01 smart plug support

---

config/ge/26933-motion-dimmer.xml
config/manufacturer_specific.xml

Still trying to work out all the details of this device (especially the motion sensor), but this adds support for the configuration parameters.

Add GE 26933 Smart Motion Dimmer

---

.gitignore

The file appears to be a build product and should not be in source control.

Ignore ozw_config

---

config/manufacturer_specific.xml
config/qubino/ZMNHWD1.xml

Implemented Qubino Flush RGBW Dimmer configuration

Qubino Flush RGBW Dimmer configuration

---

config/shenzen_neo/nas-wr01z.xml

Fix nas-wr01z.xml wrong labels as described in issue #1208 also some descriptions changed according to the manual.

Fix nas-wr01z.xml wrong labels #1208

---

config/manufacturer_specific.xml
config/philio/psp05-d.xml
distfiles.mk

Tested.
I'm new to github, so bare with me if I make any mistakes. Advice me if needed.

Added Philio PSP05-D Motionsensor Outdoor

---

cpp/src/aes/aes.h
cpp/src/value_classes/Value.h
cpp/src/value_classes/ValueList.cpp
cpp/src/value_classes/ValueList.h

During the compilation in linux with the -pedantic fleg I came across the minor warnings that I have fixed.

Fix compile warnings

---

cpp/build/winRT/vs2015/OpenZWave.vcxproj
cpp/build/winRT/vs2015/OpenZWave.vcxproj.filters
cpp/build/windows/vs2010/OpenZWave.vcxproj
cpp/build/windows/vs2010/OpenZWave.vcxproj.filters

Bitfield.cpp was missing from Windows build, causing linking to fail

Add bitfield.cpp to vcxproj files

---

config/manufacturer_specific.xml
config/trane/TZEMT524AA21MA.xml
distfiles.mk

No thermostat documentation available; copied verbatim from existing
TZEMT400AB32MAA.xml.

Adding Trane TZEMT524AA21MA thermostat

---

config/manufacturer_specific.xml
config/zooz/zse33.xml

Added Zooz ZSE33 Smart Chime

---

config/ge/14282-plugin-switch.xml
config/manufacturer_specific.xml
distfiles.mk

http://products.z-wavealliance.org/products/1437

Add GE plug-in 2-outlet smart switch

---

config/fibaro/fgd212.xml
config/fibaro/fgs211.xml
config/fibaro/fgs212.xml
config/fibaro/fgs213.xml
config/fibaro/fgs221.xml
config/fibaro/fgs222.xml
config/fibaro/fgs223.xml

See https://github.com/OpenZWave/open-zwave/issues/1251

Corrected max_associations for Fibaro devices

---

config/manufacturer_specific.xml
config/popp/700168.xml
distfiles.mk

Added support for POPP Z-Rain

---

cpp/build/windows/vs2008/OpenZWave.vcproj
cpp/examples/windows/MinOZW/Main.cpp

Fix Visual Studio 2008 project

---

config/manufacturer_specific.xml
config/zooz/zen20.xml
config/zooz/zen23.xml
config/zooz/zen24.xml

ZEN23 - http://a.co/38I7fJ1
ZEN24 - http://a.co/2VGVCDs

Added Zooz ZEN20/23/24 configs

---

config/manufacturer_specific.xml
config/vision/zl7261.xml
distfiles.mk

<http://products.z-wavealliance.org/products/1980>

Add Vision plug-in energy monitor

---

config/manufacturer_specific.xml
config/shenzen_neo/ls02ch.xml

initial commit, tested with own device

Neo Coolcam 2 channel light switch

---

config/manufacturer_specific.xml
config/shenzen_neo/ls01ch.xml

Neo Coolcam Light Switch (1 channel)

---

config/manufacturer_specific.xml
config/zooz/zen06.xml
config/zooz/zen21.xml
config/zooz/zen22.xml
config/zooz/zen22v2.xml
config/zwp/WD-100.xml
distfiles.mk

zooz zen06, zen21, zen22, zen22 V2
zwave products WD-100

add new device configs

---

config/ge/14291-switch.xml
config/ge/14292-toggle-switch.xml
config/ge/14295-dimmer-toggle.xml
config/manufacturer_specific.xml

Updated the configs for several GE/Jasco devices I have. Confirmed working with my devices. Big enhancement: double tap works for these devices now!

Update device info for several GE/Jasco switches

---

config/aeotec/zw100.xml

According to 1.07 FW (and 1.08 FW as well) data sheet.

Updated 201 description

---

config/manufacturer_specific.xml
config/remotec/zts-500.xml

This should include the changes mentioned in PR 1334.

Add Remotec ZTS-500 (USA model)

---

config/shenzen_neo/ls02ch.xml

Seems one of the config parameters was wrong

Update LS02ch config

---

config/dome/0002.xml
config/manufacturer_specific.xml
distfiles.mk

[Dome Water Shut-Off Valve](https://domeha.com/z-wave-water-main-shut-off-valve)
Setup: [Setup.pdf](https://s3.amazonaws.com/shopify-custom-fields/domeha.myshopify.com/fields/products/user_manual/8659646086/Dome%20Water%20Main%20Shut-Off%20Manual.pdf)
Manual: [Manual.pdf](https://s3.amazonaws.com/shopify-custom-fields/domeha.myshopify.com/fields/products/technical_manual/8659646086/Dome%20Water%20Main%20Shut-Off%20Advanced%20Manual.pdf)
`make dist-update` added a few extra files to _distfiles.mk_. If they shouldn't be added yet, I'll fix the commit.

Adding Dome Water Shut-Off Valve 021f:0003:0002

---

config/shenzen_neo/nas-ab01z.xml

Fixed the labels to allow openzwvae to set the values as this caused an exception

Updated Alarm/Door index labels

---

config/manufacturer_specific.xml

1) Added GE 14288 device
2) Added configuration to existing GE 45605

Added GE outlet devices

---

config/zooz/zen21.xml

Added configuration parameters as defined in the ZEN21 product manual

Update zen21.xml to include configuration params

---

config/logicsoft/ZHC5010.xml

- v2.03 includes new configuration directives and also support S0 secure inclusion mode
- Improved on all configuration directives text
- Added MULTI CHANNEL ASSOCIATION CLASS support.
- OpenZWave users (Domoticz, etc.) now out-of-box can use all four buttons

Updated LogicSoft ZHC5010 config file for v2.03 firmware.

---

cpp/src/command_classes/ManufacturerProprietary.cpp

also fixed indentation problems

Fixed nullpointer issue

---

cpp/src/command_classes/ThermostatMode.cpp
cpp/src/command_classes/ThermostatMode.h

Adds new thermostate modes introduced with V2 and V3: Full Power and Manufacturer_Specific
see #1341

Add support for ThermostatMode V3

---

config/manufacturer_specific.xml
config/philio/pan06.xml

Adding support for Philio PAN06

Request to add support for Philio PAN06

---

config/manufacturer_specific.xml

Fortezz WWA-01AA Water and Freeze Alarm
GE 45601 Advanced Remote
Leviton VRCZ4-MRZ 4-Button Zone Controller with Switch

Add additional Z-Wave devices

---

config/hank/hkzw-rgb01.xml
config/hank/hkzw-so03.xml
config/manufacturer_specific.xml
distfiles.mk

Hank (monoprice) RGB bulb - hkzw-rgb01
Hank (monoprice) Smart Plug - hkzw-so03

add new devices

---

config/manufacturer_specific.xml

This appears to have exactly the same parameters as the NAS-WS02Z sensor.

Add Neo Coolcam NAS-WS01Z flood sensor

---

config/manufacturer_specific.xml
config/oomi/ft100.xml
config/oomi/ft111.xml

Added FT100 (essentially exactly the same as the Aeotec ZW100)
Added FT111 (essentially exactly the same as the Aeotec ZW111)

Add Oomi manufacturer and devices

---

config/assa_abloy/ConexisL1.xml
config/assa_abloy/KeyfreeConnected-plus.xml
config/manufacturer_specific.xml

Added YKFCON https://products.z-wavealliance.org/products/2743
Added SD-L1000-CH https://products.z-wavealliance.org/products/2535

 Add Yale ConexisL1 and Yale KeyfreeConnected-plus

---

config/manufacturer_specific.xml
config/zooz/zen15.xml
config/zooz/zse40.xml

Added Zooz ZEN15 config.
Update Zooz ZSE40 config to reflect the new version of this sensor, even though it has the same product type and ID.  The vendor sent me a sample to test with along with parameter documentation.  Parameters have changed slightly, but the Product Type and ID has changed so I updated the config for the latest version.

New Sensor, and updated sensor

---

config/linear/WD500Z5-1.xml
config/manufacturer_specific.xml
distfiles.mk

Added entry to manufacturer_specific.xml and added device specific file linear/wd500z5-1.xml, including configuration parameters and central scene parameters for this device.

WIP: Add Linear/GoControl WD500Z5-1

---

config/manufacturer_specific.xml

Add another id for GD00Z-4 Garage Door Opener Remote Controller
Add GD00Z-7 Garage Door Opener Remote Controller

[master] Add another id for GD00Z-4 and add GD00Z-7

---

config/manufacturer_specific.xml

Add another id for GD00Z-4 Garage Door Opener Remote Controller
Add GD00Z-7 Garage Door Opener Remote Controller

[Dev] Add another id for GD00Z-4 and add GD00Z-7

---

config/fibaro/fgdw2.xml

Based on https://manuals.fibaro.com/content/manuals/en/FGDW-002/FGDW-002-EN-T-v1.1.pdf.

Fixed "Temperature Offset" size.

---

config/august/asl-03.xml
config/manufacturer_specific.xml
distfiles.mk

Adding support for the August Smart Lock Pro. This is effectively a fix/update to PR #1413.
Note that unfortunately I cannot test this, as I do not yet have a Z-Wave controller for my RPi.

Add August Smart Lock Rev 3 (ASL-03)

---

config/zipato/RGBBulb2.xml

I now changed the zipato/RGBBulb2.xml file
Tested in on my server.
root@server01:/opt/open-zwave# ./MinOZW | grep Node011
2018-03-07 16:21:59.117 Detail, Node011, AdvanceQueries queryPending=0 queryRetries=0 queryStage=None live=1
2018-03-07 16:21:59.117 Detail, Node011, QueryStage_ProtocolInfo
2018-03-07 16:21:59.117 Detail, Node011, Queuing (Query) Get Node Protocol Info (Node=11): 0x01, 0x04, 0x00, 0x41, 0x0b, 0xb1
2018-03-07 16:21:59.117 Detail, Node011, Queuing (Query) Query Stage Complete (ProtocolInfo)
2018-03-07 16:21:59.117 Info, Node011, Initializing Node. New Node: false (false)
2018-03-07 16:21:59.118 Detail, Node011, Notification: NodeNew
2018-03-07 16:21:59.118 Detail, Node011, Notification: NodeAdded
2018-03-07 16:22:17.041 Info, Node011, Sending (Query) message (Callback …

This commit fixes #1457 Blue color value not reported by ZIPATO BULB 2

---

config/homeseer/hs-ws200plus.xml
config/manufacturer_specific.xml

To test I ran this in the latest version of home assistant.  I also ran `make xmltest`.
Config was derived from the official manual for the HS-WS200+

Add support for the Homeseer HS-WS200+ wall switch

---

config/manufacturer_specific.xml
config/steinel/rs-led-d2.xml

Create config for Steinel RS LED D2 Z-Wave

---

config/inovelli/nzw30.xml
config/inovelli/nzw31.xml
config/inovelli/nzw97.xml
config/manufacturer_specific.xml
distfiles.mk

Adding configuration options and parameters for Inovelli Rocker switch and dimmer

Configs for Inovelli nzw30, nzw31, nzw97

---

config/homeseer/hs-wd100plus.xml

Reverts OpenZWave/open-zwave#1530

Revert "Fix parameter size and allowed values for HS-WD100+"

---

config/telldus/TZWP102.xml

Added "Default xx" for each index so the user can see what default value was is.
Found an error for index 17, missing text in Help section

Added Default text. Corrected index 17

---

config/thermofloor/heatitztrm2.xml
distfiles.mk

Added missing configuration parameters and associoation groups

Updated Thermofloor Heatit Z-TRM2 Configuration file

---

config/hank/hkzw-ms02.xml
config/manufacturer_specific.xml

Checked for valid XML. Tested and working.

Add device: Hank HKZW-MS02 Motion Sensor

---

Makefile
cpp/build/Makefile
cpp/src/platform/unix/ThreadImpl.cpp

A few changes to allow the Dev branch to compile on FreeBSD.

Compilation fixes for FreeBSD

---

config/thermofloor/heatitztrm2.xml

Sensor multilevel differents temperature labels

Updated Thermofloor Heatit Z-TRM2 config

---

config/manufacturer_specific.xml
config/steinel/xled-home-2.xml
distfiles.mk

For some reason dist-update introduced two more changes (two additional files). Maybe the dist-update was missed for earlier updated. I kept them in the pull request for now even though they are not related. Let me know if I should submit a clean version of the pull request without these two changes (means I would need to manually adjust the distfiles after running dist-update).
Device: [https://products.z-wavealliance.org/products/2290/](https://products.z-wavealliance.org/products/2290/)

adding Steinel XLED home 2 device

---

config/manufacturer_specific.xml
config/qubino/ZMNHXDx.xml
distfiles.mk

Support for Qubino 3-phase meter. [Manual][1].
I'm not sure about the `<CommandClass id="142" ForceInstances="true" />` and `<CommandClass id="96" mapping="endpoints" />`. With those the device seems to work best. Without the _96_ it does not properly report some values (and there's 5 instances then; and something like "previous value" is then available for i.e. `Total kWh`; confusing). 😕 Seems like Qubino devices are somewhat specific. Maybe somebody can comment. I'm ready to test it as much as possible.
The result in OZW's Control Panel is then this:
Which looks good-ish to me. The last _Unknown_ value I think is _var_. Can I somehow provide name for it? Not sure what the the remaining 3 _Unknown_ values on top are. Looks like something per-phase (see below), maybe `kWh` based on the …

Support for Qubino 3-phase meter

---

cpp/build/Makefile
cpp/examples/MinOZW/Makefile
cpp/hidapi/libusb/hid.c
cpp/src/platform/unix/SerialControllerImpl.cpp

relevant issue: https://github.com/OpenZWave/python-openzwave/issues/123

support building on SmartOS

---

config/manufacturer_specific.xml

Updated manufacturer_specific.xml

---

config/inovelli/nzw1201.xml
config/inovelli/nzw30.xml
config/inovelli/nzw31.xml
config/inovelli/nzw36.xml
config/inovelli/nzw37.xml
config/inovelli/nzw39.xml
config/inovelli/nzw96.xml
config/manufacturer_specific.xml

Adding some additional devices and fixing just a couple of configuration parameters / adding association groups.

Updating collection of Inovelli devices 

---

config/manufacturer_specific.xml
config/mcohome/a8-9.xml
distfiles.mk

Again, one of my first pull request, please bear with me :) 
Not sure what all the parameters exactly do, but got this straight from the manual, seem to be working with my device.

added Mcohome A8-9 (9 in 1 Multi-sensor)

---

config/remotec/zts-110.xml
config/remotec/zts-500.xml

Fahrenheit is hard to spell :)

Minor spelling corrections

---

cpp/src/Localization.cpp
cpp/src/Localization.h
cpp/src/value_classes/Value.cpp

There was some mixup between Help and Label strings, causing GetLabels to not work for most values (SetHelp was used instead of SetLabel when loading the XML)
/cc @Fishwaldo

Fix GetLabel for values

---

config/eurotronic/eur_spiritz.xml
config/manufacturer_specific.xml
cpp/src/Driver.cpp

try to merge changes of @tobiasgraf repo "Eurotronic Spirit Z" to newest master branch of openzwave

Add support for Eurotronics Spirit Z

---

config/thermofloor/heatit033.xml

- Added missing help descriptions

Fixed a few byte and short errors

---

config/fibaro/fgs213.xml
config/fibaro/fgs223.xml

The configuration items of type list did not contain a min and max property. This property could be used in a UI to validate the specified value is within the allowed range.

Added min and max properties to all configuration items for Fibaro FGS2x3.xml

---

config/manufacturer_specific.xml

Thanks to aseelert there is an update with a new mh7h.xml (proposed) which needs some additional definitions in the manufacturer xml.

update for MH7H by MCO Home

---

config/mcohome/mh7h.xml

Thanks to aseelert this is a config file for the MH7H by MCO Home.

Config file for the MH7H by MCO Home

---

config/linear/WA00Z-1.xml

Added a valueID for each switch. Without this, the button
presses don't get reported.

Add central scene support for WA00Z

---

config/manufacturer_specific.xml
config/schlage/BE469ZP.xml

Added Schlage Connect Smart Deadbolt model BE469ZP. Tested using OpenZwave Control Panel.

Added Schlage BE469ZP

---

config/manufacturer_specific.xml
config/zooz/zen20v2.xml
config/zooz/zse19.xml

Added Zooz ZSE19 and Zooz ZEN20 v2.0 Devices.

Added Zooz ZSE19 and Zooz ZEN20 v2.0 Devices

---

config/heltun/he-zw-therm-fl2.xml
config/manufacturer_specific.xml

make xmltest passes OK. I have tested this configuration with the OZW control panel and successfully set the clock.  All the settings are straight from the documentation:  https://drive.google.com/open?id=1AKHXZHyFCfpo_2Wd0XrisgIwilpezM7Q  There are so many settings I have a spreadsheet to generate the value items.

Support for the Heltun HE-ZW-THERM-FL2 Heating Thermostat

---

config/manufacturer_specific.xml
config/shenzen_neo/nas-wr01ze.xml

Update Neo CoolCam NAS-WR01ZE based on newly created shenzen_neo config: "nas-wr01ze.xml"

Update Neo CoolCam NAS-WR01ZE

---

config/thermofloor/heatit021.xml

Heatit Thermostat TF 021

---

config/manufacturer_specific.xml
config/tronika/zv9040.xml

add support for Tronika Dimmer ZV9040 

---

config/manufacturer_specific.xml

Add Fibaro FGMS001-ZW5 Motion Sensor v3.3

---

config/fibaro/fgbs222.xml
config/manufacturer_specific.xml
distfiles.mk

Changes for Fibaro FGBS-222 Smart Implant
Module: https://www.fibaro.com/us/products/smart-implant/
Documentation: https://manuals.fibaro.com/content/manuals/en/FGBS-222/FGBS-222-EN-T-v1.0.pdf
Everything seems working fine to me, except lifeline association. I have to enable the polling to get updated values. I don't have enough zwave knowledge to find what is wrong.

Fibaro FGBS-222 Smart Implant

---

config/honeywell/th6320zw2003.xml
config/manufacturer_specific.xml

Add Honeywell Lyric T6 Pro Z-Wave Plus Smart Thermostat TH6320ZW2003
https://products.z-wavealliance.org/products/2583

Add Honeywell Lyric T6 Pro Z-Wave Plus Smart Thermostat TH6320ZW2003

---

cpp/build/winRT/vs2015/OpenZWave.vcxproj
cpp/build/winRT/vs2015/OpenZWave.vcxproj.filters

This enables UWP to compile for the latest dev branch, and adds ARM64.
Also rearranged file contents for easier sync with the desktop project in the future.
I'd prefer this gets merged prior to the 1.6 release, so we can ship a .net package on top of it

Update WinRT/UWP build

---

config/manufacturer_specific.xml
config/zooz/zen25.xml
distfiles.mk

This adds support for the Zooz S2 Double Plug with USB Port.

Add Zooz ZEN25 S2 Double Plug

---

config/heiman/HS2WD-Z.xml
config/manufacturer_specific.xml

I added Heiman Indoor Siren config
<Product type="8009" id="1000" name="Indoor Siren HS2WD-Z" config="heiman/HS2WD-Z.xml"/>

add device config Heiman Indoor Siren

---

config/manufacturer_specific.xml
config/qubino/ZMNKIDx.xml

Added the configuration xml for the "Qubino Flush Thermostat OnOff 2" device and an entry into the manufacturer_specific.xml.

Added the Flush Thermostat OnOff 2

---

config/manufacturer_specific.xml
config/zooz/zen21v2.xml
distfiles.mk

Added a different file to differentiate from older hardware

Zooz ZEN21 updates for Firmware v3

---

config/manufacturer_specific.xml

Added the Kwikset SmartCode 914 Z-Wave plus deadbolt
The SmartCode 914 shows as "Unknown", this should fix that problem.

Add KwikSet SmartCode 914

---

config/qubino/ZMNHADx.xml
cpp/build/testconfigversions.cfg

Update Qubino ZMNHADx

---

config/manufacturer_specific.xml
config/zwp/PA-100.xml
cpp/build/testconfigversions.cfg

Update device config PA-100 + add to database

---

config/fibaro/fgmszw5.xml
cpp/build/testconfigversions.cfg

Set ForceInstances to false on Multi-Channel Assoc of FGMS-001 ZW5

---

cpp/src/Node.h

Reverts OpenZWave/open-zwave#1859

Revert "Added missing include for shared_ptr"

---

config/shenzen_neo/nas-pd02z.xml
cpp/build/testconfigversions.cfg

https://github.com/OpenZWave/open-zwave/issues/1866

Add support for "temperature" model of NAS-PD02Z

---

config/manufacturer_specific.xml

Add Zooz ZEN25 to list of devices in manufacturer_specfic.xml

---

config/fibaro/fgwds221.xml
config/manufacturer_specific.xml
cpp/build/testconfigversions.cfg

Added "FGWDS221 Walli Double Switch" to manufacturer_specifiec.xml
Added /config/fibaro/fgwds221.xml file with all z-wave config's from https://products.z-wavealliance.org/products/3395/configs

Added Fibaro FGWDS221 Walli Double Switch

---

cpp/src/Node.cpp
cpp/src/Node.h
cpp/src/command_classes/CommandClass.cpp
cpp/src/command_classes/CommandClass.h
cpp/src/command_classes/MultiInstance.cpp
cpp/src/command_classes/ThermostatSetpoint.cpp
cpp/src/command_classes/ThermostatSetpoint.h
cpp/src/command_classes/Version.cpp
distfiles.mk

Reverts OpenZWave/open-zwave#1876 till we can find a better fix.

Revert "Change Interview Order to ensure we have the CC Version"

---

cpp/build/testconfigversions.cfg

Adds missing single quotes to Revision
Removes a few stale references (renamed files)

regenerate testconfigversions.cfg

---

config/linear/WS15Z-1.xml
config/linear/WT00Z-1.xml
cpp/build/testconfigversions.cfg

These devices support group 1 associations to update status of associated devices. (On off and dim in the case of the WD500Z.

Linear WT001 and WS15Z group 1 associations

---

config/manufacturer_specific.xml
cpp/build/testconfigversions.cfg

Add Fibaro System device FGFS101 Zwave+ Flood Sensor - added entry for new device ID for the AU region

Update manufacturer_specific.xml for FGFS101 Zwave+ Flood Sensor

---

README.md
cpp/src/DoxygenMain.h

Should fix "Outdated info in readme.md and on website?" #1961

Update README.md and DoxygenMain.h

---

cpp/src/value_classes/ValueID.h
cpp/test/ValueID_test.cpp
dist/openzwave.spec

No functional changes.
GetValueStoreKey has 2 overloads and they return identical results, the math is correct, this was questioned here: https://github.com/domoticz/domoticz/issues/3727

Make GetValueStoreKey public and add tests

---

config/manufacturer_specific.xml
config/widom/DRY.xml
cpp/build/testconfigversions.cfg

Added new device: 
Manufacturer id=0149
Product:
config=widom/DRY.xml, id=0900, name=DRY Smart Dry Contact Switch, type=1214

Added config file WiDom Smart Dry Contact

---

cpp/src/value_classes/Value.cpp
cpp/src/value_classes/Value.h

Reverts OpenZWave/open-zwave#2008
Did you even compile test this?

Revert "Make set after get optional"

---

cpp/src/Driver.cpp
dist/openzwave.spec

Before PR
Node002, ERROR: Dropping command, expected response not received after 1 attempt(s).
After PR
ode002, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SensorMultilevelCmd_Get (Node=2): 0x01, 0x0b, 0x00, 0x13, 0x02, 0x04, 0x31, 0x04, 0x01, 0x00, 0x25, 0x20, 0xd0"

Add message details to log of dropped message

---

config/manufacturer_specific.xml
cpp/build/testconfigversions.cfg
distfiles.mk

Came across a Fibaro flood sensor variant with type/id=0b01/2003.
Also updated `distfiles.mk` for files that were missed by a previous commit.

Add fibaro flood sensor

---

config/manufacturer_specific.xml
cpp/build/testconfigversions.cfg

These were misidentified in my HomeAssistant setup but it appears it's just needs leading zeros.

Update ID and type for HomeSeer sensors

---

config/Localization.xml

Fix type of Note/Node in Localization.xml.

Fix type in Localization.xml

---

config/honeywell/39351-ZW3010.xml
config/manufacturer_specific.xml

I think I have this right. Please review. 
See comments at #2134

Add honeywell 39351-ZW3010

---

cpp/src/command_classes/SensorBinary.cpp

do not sychronize a BASIC set/report when Get is not supported

---

cpp/src/command_classes/Color.cpp

Fix for #1588

---

config/zooz/zen16.xml

Updated config for Zooz Zen16 firmware 1.02.

Update for Zooz Zen16

---

config/manufacturer_specific.xml

AU roller shutter, AU door sensor

Fibaro AU FGRM222, FGS213

---

config/manufacturer_specific.xml
config/schlage/BE469.xml

Refresh the DoorLock if we get a change on a Notification CC with Index 6 (Access Control)
Fixes #2246

Update BE469.xml TriggerRefreshValue

---

config/zooz/zen21v3.xml

Update description for parameter 12, this switch is not a dimmer and incorrectly references a value not applicable to this switch

Update ZEN21v3 parameter 12 description

---

config/inovelli/lzw36.xml
config/manufacturer_specific.xml

Files pulled right from manufacturers "How to install this device in Home Assistant" config files, with the static central scene reports removed for OZW 1.6. 
https://community.inovelli.com/t/lzw36-openzwave-beta-scene-issues/4010

Add support for Inovelli lzw36 fan-switch combo

---

config/kwikset/smartcode.xml

Same fix as #2256, but for Smart Code / Obsidian line.

[FIX] Smartcode.xml TriggerRefreshValue idx 0=>6

---

config/zooz/zen20v2.xml

The new 2.03 firmware adds some feature and new config parameters. There is unfortunately a slight hardware difference between 2.02 and 2.03, but they share the same ID.

Update Parameters for Zen20 2.03 

---

config/kwikset/888.xml

@MagmaiKH provided a manual with the config params and i used that to add the missing param block.

added config params to kwikset 888

---

cpp/src/Scene.cpp
cpp/src/command_classes/WakeUp.cpp
cpp/src/platform/HttpClient.cpp
cpp/src/value_classes/ValueStore.cpp

After erase the iterator is undefined. Found these while looking for something else. Fixed them.

Fixed iterator deletion

---

config/manufacturer_specific.xml

Add support for NEO Siren Australia

Add support for NEO Siren Australia

---

config/ge/26932-motion-dimmer.xml
config/manufacturer_specific.xml

26932 Dimmer appears to be identical to 26933:
https://products.z-wavealliance.org/products/2093

Add support for GE/Jasco 26932 In-Wall Smart Motion Dimmer

---

config/fakro/arzsolar.xml
config/fakro/zrh12.xml
config/manufacturer_specific.xml

Added manufacturer files for Fakro:
1. AZR Solar Roof Window Roller Shutter
2. ZRH12 Portable Remote Controller

New manufacturer files for ARZ Solar and ZRH12 Fakro devices.

---

config/qubino/ZMNHCDx.xml

- Added <ForceInstances>false</ForceInstances> to associations class
- Reformatted XML file.

Fixed a problem with lifeline group 1.1

---

config/device_configuration.xsd
cpp/build/testconfigversions.cfg

There seems to be validation error cased by duplicate entries in one of the xml schema files.

Fix validation error in XML Schema - duplicate entries

---

config/aeotec/zw111.xml
config/aeotec/zw116.xml
config/aeotec/zw132.xml

Reverts OpenZWave/open-zwave#2517
Close #2529

Revert "Add basic command class to Aeotec switches and dimmers"

---

config/manufacturer_specific.xml
config/thermofloor/heatit-zdim.xml
config/thermofloor/heatit021-v1.92.xml

Fixes https://github.com/OpenZWave/open-zwave/issues/2528 and https://github.com/OpenZWave/open-zwave/pull/1758

Adding support for heatit TF021 with FW >= 1.92, fixing z-dim bug

---

config/manufacturer_specific.xml
config/thermofloor/heatitz4.xml
config/thermofloor/heatitz8.xml

Adding support for the Future Home AS white labeled version of the HeatIt Z-push button 8 device. Also fixing association groups for the HeatIt z-push devices.

Fixing heatit push button devices

---

config/manufacturer_specific.xml

Recently added to my system using PushButtonDeadbolt.xml for config, working same as previous YRD110, 210, 216.

Add Yale YRD136 push button deadbolt lock

---

config/fibaro/fgt001.xml

Firmware 4.7 adds a few more configuration settings.

Add settings for Fibaro FGT-001 firmware 4.7

---

config/fibaro/fgwds221.xml
config/fibaro/fgwds221ss.xml
config/manufacturer_specific.xml
cpp/build/testconfigversions.cfg
distfiles.mk

Adding a new entry for fgwds221 in Single switch mode (1A01)
Typo cor…rections / default value for LED frame – colour when OFF for fgwds221 Double switch (1B01)

Adding a new entry for fgwds221 in Single switch mode (1A01)

---

config/manufacturer_specific.xml
config/qubino/ZMNHMDx.xml

Adding entries for the new "Qubino Smart leak protector" device.

Smart leak protector

---

config/hank/hkzw-so08-smartplug.xml
config/manufacturer_specific.xml
cpp/build/testconfigversions.cfg
distfiles.mk

Hello,
This request adds configuration for new Hank smartplug so08, tested OK with Domoticz 2021.1 (OZW 1.6 based).
Regards.

Add Hank smartplug so08 configuration

---

cpp/src/command_classes/SwitchBinary.cpp
cpp/src/command_classes/SwitchBinary.h
cpp/src/value_classes/ValueBool.cpp
cpp/src/value_classes/ValueBool.h

Following up on pull request #2584 and #2616.
Made additions to support the supervision CC for the switch binary CC.

Supervision CC support for SwitchBinary
